import { useState } from "react";
import { ArrowRight, Check, Landmark, Plus, ReceiptText, WalletCards } from "lucide-react";

const steps = ["基础设置", "建立资金账户", "选择收支模板", "检查账本结构", "创建并校验"];
const templateAccounts = ["Expenses:Food", "Expenses:Transport", "Expenses:Shopping", "Expenses:Home", "Income:Salary", "Income:Other"];

type Asset = { name: string; kind: "Assets" | "Liabilities"; balance: string };
export type OnboardingPayload = { title: string; currency: string; startDate: string; assets: { account: string; currency: string; openingBalance: string }[]; categories: string[] };

export function OnboardingPrototype({ onCreate, creating = false, error = "", waiting = false }: { onCreate?: (payload: OnboardingPayload) => void; creating?: boolean; error?: string; waiting?: boolean }) {
  const [step, setStep] = useState(0);
  const [title, setTitle] = useState("我的生活账本");
  const [currency, setCurrency] = useState("CNY");
  const [startDate, setStartDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [assets, setAssets] = useState<Asset[]>([{ name: "Assets:Cash", kind: "Assets", balance: "500" }, { name: "Assets:Bank:Checking", kind: "Assets", balance: "12800" }]);
  const [template, setTemplate] = useState(true);
  const [categories, setCategories] = useState<string[]>([]);
  const addAsset = () => setAssets((value) => [...value, { name: "", kind: "Assets", balance: "" }]);
  const updateAsset = (index: number, patch: Partial<Asset>) => setAssets((value) => value.map((item, i) => i === index ? { ...item, ...patch } : item));
  const allCategories = [...(template ? templateAccounts : []), ...categories.filter(Boolean)];
  const accountTree = [...assets.filter((item) => item.name).map((item) => item.name), ...allCategories, "Equity:Opening-Balances"];
  const create = () => onCreate?.({ title, currency, startDate, assets: assets.filter((item) => item.name).map((item) => ({ account: item.name, currency, openingBalance: item.balance })), categories: allCategories });
  return <main className="min-h-screen bg-paper px-4 py-6 text-ink sm:px-8 lg:px-12 lg:py-10"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[260px_minmax(0,1fr)]">
    <aside className="lg:pt-6"><p className="text-xs font-semibold tracking-[0.16em] text-brand">FIRST LEDGER</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.035em]">建立你的财务地图</h1><p className="mt-3 text-sm leading-6 text-stone">从真实账户出发，逐步生成一份可以开始记账的 Beancount 账本。</p><ol className="mt-10 space-y-4">{steps.map((label, i) => <li key={label} className={`flex items-center gap-3 text-sm ${i === step ? "font-semibold text-ink" : i < step ? "text-olive" : "text-stone"}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs ${i < step ? "bg-olive text-paper" : i === step ? "bg-brand text-paper" : "bg-sand"}`}>{i < step ? <Check className="h-4 w-4" /> : i + 1}</span>{label}</li>)}</ol></aside>
    <section className="min-h-[650px] rounded-[1.5rem] bg-panel p-6 shadow-[0_18px_48px_oklch(0.20_0.012_255/0.10)] sm:p-10">
      {step === 0 && <div className="max-w-xl"><p className="text-sm text-stone">第一步</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">先给这本账一个名字</h2><label className="mt-10 block text-sm font-medium">账本名称<input value={title} onChange={(e) => setTitle(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-4 outline-none focus-visible:ring-4 focus-visible:ring-brand/20" /></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">日常记账货币<select value={currency} onChange={(e) => setCurrency(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-4"><option value="CNY">CNY, 人民币</option><option value="USD">USD, 美元</option><option value="HKD">HKD, 港币</option></select></label><label className="block text-sm font-medium">开始记账日期<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="mt-2 h-12 w-full rounded-xl border border-line bg-paper px-4" /></label></div></div>}
      {step === 1 && <div><p className="text-sm text-stone">第二步</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">建立资金账户</h2><p className="mt-3 text-sm leading-6 text-stone">每一行都会变成一个 Assets 或 Liabilities 账户。期初余额会生成一笔与 Equity:Opening-Balances 配对的交易。</p><p className="mt-2 text-xs leading-5 text-stone">负债请填写你欠下的正数金额，账本会自动按 Beancount 的贷方方向记入。</p><div className="mt-8 space-y-3">{assets.map((asset, i) => <div key={i} className="grid gap-3 rounded-2xl bg-paper p-4 sm:grid-cols-[140px_1fr_150px]"><select value={asset.kind} onChange={(e) => { const kind = e.target.value as Asset["kind"]; updateAsset(i, { kind, name: asset.name ? asset.name.replace(/^(Assets|Liabilities):/, `${kind}:`) : `${kind}:` }); }} className="h-11 rounded-xl border border-line bg-panel px-3 text-sm"><option value="Assets">资产</option><option value="Liabilities">负债</option></select><input value={asset.name} onChange={(e) => updateAsset(i, { name: e.target.value })} placeholder="Assets:Bank:Checking" className="h-11 rounded-xl border border-line bg-panel px-3 text-sm" /><label className="text-xs text-stone">期初余额<input value={asset.balance} onChange={(e) => updateAsset(i, { balance: e.target.value })} inputMode="decimal" placeholder="0" className="mt-1 h-9 w-full rounded-lg border border-line bg-panel px-3 text-sm text-ink" /></label></div>)}</div><button type="button" onClick={addAsset} className="mt-4 inline-flex h-10 items-center gap-2 text-sm font-medium text-brand"><Plus className="h-4 w-4" />添加资金账户</button></div>}
      {step === 2 && <div><p className="text-sm text-stone">第三步</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">选择收支分类口径</h2><p className="mt-3 text-sm leading-6 text-stone">从一个日常生活模板开始，随后仍可在应用内新增、合并或调整分类。</p><button type="button" onClick={() => setTemplate(!template)} className={`mt-10 flex w-full items-start gap-4 rounded-2xl p-5 text-left ${template ? "bg-tag shadow-[inset_0_0_0_1px_oklch(var(--color-brand)/0.25)]" : "bg-paper shadow-[inset_0_0_0_1px_oklch(var(--color-line))]"}`}><ReceiptText className="h-5 w-5 text-brand" /><span><b className="block">日常个人财务</b><small className="mt-1 block text-sm text-stone">餐饮、交通、购物、居家，加上工资与其他收入。</small></span>{template && <Check className="ml-auto h-5 w-5 text-olive" />}</button><div className="mt-5 space-y-2">{categories.map((value, index) => <input key={index} value={value} onChange={(e) => setCategories((items) => items.map((item, i) => i === index ? e.target.value : item))} placeholder="Expenses:Health 或 Income:Freelance" className="h-11 w-full rounded-xl border border-line bg-paper px-3 text-sm" />)}</div><button type="button" onClick={() => setCategories((items) => [...items, ""])} className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-brand"><Plus className="h-4 w-4" />添加自定义分类</button></div>}
      {step === 3 && <div><p className="text-sm text-stone">第四步</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">检查将要创建的账本</h2><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-paper p-5"><p className="text-xs font-semibold tracking-[0.12em] text-stone">ACCOUNT TREE</p><ul className="mt-4 space-y-2 font-mono text-sm">{accountTree.map((item) => <li key={item} className="flex gap-2"><span className="text-brand">└</span>{item}</li>)}</ul></div><div className="rounded-2xl bg-ink p-5 font-mono text-xs leading-6 text-paper"><p className="text-white/50">; opening balances</p>{assets.filter((item) => item.name && item.balance).map((item) => <p key={item.name}>{startDate} * "期初余额"<br />&nbsp;&nbsp;{item.name} {item.balance} {currency}<br />&nbsp;&nbsp;Equity:Opening-Balances</p>)}</div></div></div>}
      {step === 4 && <div className="max-w-xl"><p className="text-sm text-stone">第五步</p><h2 className="mt-2 text-4xl font-semibold tracking-[-0.04em]">创建并等待校验</h2><div className="mt-10 rounded-2xl bg-paper p-5"><p className="font-medium">{title}</p><p className="mt-2 text-sm leading-6 text-stone">将提交到 GitHub main，indexer 会立即拉取、执行 bean-check 并发布首个账本版本。</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-sand"><div className={`h-full rounded-full bg-brand ${waiting ? "w-4/5 animate-pulse" : "w-2/5"}`} /></div><p className="mt-3 text-sm text-stone">{waiting ? "已提交，正在等待 indexer 校验。" : "校验通过前不会进入主界面。"}</p></div></div>}
      {error && <p className="mt-5 text-sm text-danger">{error}</p>}<div className="mt-14 flex items-center justify-between border-t border-line pt-6"><button type="button" onClick={() => setStep(Math.max(0, step - 1))} className="h-11 px-3 text-sm text-stone disabled:opacity-0" disabled={step === 0 || waiting}>上一步</button><button type="button" onClick={() => step === 4 ? create() : setStep(Math.min(4, step + 1))} disabled={creating || waiting} className="inline-flex h-11 items-center gap-2 rounded-xl bg-brand px-5 text-sm font-medium text-paper transition-transform active:scale-[0.97] disabled:opacity-60">{step === 4 ? (waiting ? "正在等待校验…" : creating ? "正在创建…" : "创建账本") : "继续"}<ArrowRight className="h-4 w-4" /></button></div>
    </section></div></main>;
}
