export type TimePreset = "week" | "month" | "quarter" | "year" | "all" | "custom";
export type TimeRange = { start: string; end: string; preset: TimePreset };
export type Summary = { income: number; expense: number; net: number; days: Record<string, { income: number; expense: number }>; categories: Record<string, number> };
export type MetadataValue = string | number | boolean;
export type Txn = { date: string; payee: string; narration: string; metadata?: Record<string, MetadataValue>; tags?: string[]; postings: { account: string; amount: number; currency?: "CNY" }[]; source: { file: string; line: number } };
export type BudgetRow = { account: string; budget: number; spent: number; remaining: number; ratio: number | null };
export type ReconcileRow = { account: string; label: string; ledgerBalance: number; status: "asserted" | "pending"; lastAssertion: { date: string; amount: number; currency: "CNY" } | null };
export type AccountGroup = "cash" | "credit" | "wealth" | "receivable" | "expense" | "income" | "equity" | "other";
export type AccountStatus = {
  account: string;
  status: "green" | "red" | "yellow" | "grey";
  lastEntryDate: string | null;
  lastEntryType: "balance" | "transaction" | null;
  assertionAmount: number | null;
  computedBalance: number | null;
};
export type AccountView = { account: string; openDate: string; closeDate: string | null; currency: "CNY"; alias: string | null; label: string; group: AccountGroup; active: boolean };
export type LedgerNotification = { id: string; insightId: string; month: string; severity: "info" | "warning" | "critical"; title: string; detail: string; amount?: number; account?: string; date?: string; status: "unread" | "read" | "dismissed" | "resolved"; createdAt: string; readAt: string | null; dismissedAt: string | null; resolvedAt: string | null; updatedAt: string };
export type PayeeAnalytics = { payee: string; amount: number; txCount: number };
export type AccountAnalytics = { account: string; amount: number; txCount: number };
export type ExpenseCategoryAnalytics = { account: string; label: string; amount: number; txCount: number; share: number | null; previousAmount: number; changeRatio: number | null; topPayees: PayeeAnalytics[] };
export type IncomeStatementCache = { income: IncomeStatementNode[]; expense: IncomeStatementNode[]; totalIncome: number; totalExpense: number; netIncome: number; expenseAnalytics?: ExpenseCategoryAnalytics[]; topPayees?: PayeeAnalytics[]; topPaymentAccounts?: AccountAnalytics[] } | null;
export type LedgerVersion = { version?: string; signature?: string; fileCount: number; latestMtimeMs: number; totalSize?: number };
export type NetWorthPoint = { date: string; assets: number; liabilities: number; netWorth: number };
export type NetWorthDelta = { baseline: NetWorthPoint | null; change: number | null; changeRatio: number | null };
export type NetWorthWindows = { latest: NetWorthPoint | null; previousMonthEnd: NetWorthPoint | null; monthChange: number | null; sixMonth: NetWorthDelta; twelveMonth: NetWorthDelta };
export type CreditCardAnalytics = { account: string; label: string; balance: number; outstanding: number; periodSpend: number; periodRepayments: number; txCount: number; repaymentCount: number; lastActivityDate: string | null };
export type LedgerCache = { summary: Summary | null; balances: Record<string, number>; txns: Txn[]; budgetRows: BudgetRow[]; netWorthRows: NetWorthPoint[]; monthEndNetWorthRows?: NetWorthPoint[]; netWorthWindows?: NetWorthWindows | null; creditCards?: CreditCardAnalytics[]; reconciliationRows: ReconcileRow[]; accounts: AccountView[]; notifications?: LedgerNotification[]; incomeStatement: IncomeStatementCache; accountStatuses: AccountStatus[]; ledgerVersion?: LedgerVersion; savedAt: number };
export type ManualKind = "expense" | "income" | "transfer";
export type ManualForm = { kind: ManualKind; date: string; payee: string; narration: string; amount: string; fromAccount: string; toAccount: string; category: string };
export type LedgerPage = "home" | "net-worth" | "transactions" | "accounts" | "budgets" | "reconcile" | "settings" | "income-statement";
export type PrivacySettings = { showHomeSummaryAmounts: boolean; showHomeCashflowChart: boolean; showAccountBalancesByDefault: boolean; showNetWorthByDefault: boolean; showIncomeStatementByDefault: boolean };
export type ThemeMode = "system" | "light" | "dark";
export type ResolvedTheme = "light" | "dark";
export type IncomeStatementNode = { account: string; label: string; amount: number; children: IncomeStatementNode[]; depth: number; txCount: number };
