export type TimePreset = "week" | "month" | "quarter" | "year" | "all" | "custom";
export type TimeRange = { start: string; end: string; preset: TimePreset };
export type Summary = { currency?: string; income: number; expense: number; net: number; days: Record<string, { income: number; expense: number }>; categories: Record<string, number> };
export type MetadataValue = string | number | boolean;
export type Txn = { date: string; payee: string; narration: string; metadata?: Record<string, MetadataValue>; tags?: string[]; postings: { account: string; amount: number; currency?: string }[]; source: { file: string; line: number; hash?: string }; pending?: { kind: "append" | "update-transaction"; operationId: string } };
export type AccountDetailRow = { date: string; payee: string; narration: string; change: number; balance: number; txn: Txn };
export type ReconcileRow = { account: string; alias?: string | null; label: string; currency: string; ledgerBalance: number; status: "asserted" | "pending"; lastAssertion: { date: string; amount: number; currency: string } | null };
export type AccountGroup = "cash" | "credit" | "liability" | "wealth" | "receivable" | "expense" | "income" | "equity" | "other";
export type AccountOperation = { kind: "create" | "update" | "disable"; date: string; account: string; alias?: string; currency?: string; group?: AccountGroup };
export type AccountStatus = {
  account: string;
  status: "green" | "red" | "yellow" | "grey";
  lastEntryDate: string | null;
  lastEntryType: "balance" | "transaction" | null;
  assertionAmount: number | null;
  computedBalance: number | null;
};
export type AccountView = { account: string; openDate: string; closeDate: string | null; currency: string; alias: string | null; label: string; group: AccountGroup; active: boolean; metadata?: Record<string, MetadataValue> };
export type AccountBalance = { account: string; currency: string; amount: number; valuationCurrency: string; valuation: number; valuationMissing?: boolean };
export type Price = { date: string; currency: string; amount: number; quoteCurrency: string };
export type LedgerNotification = { id: string; insightId: string; month: string; severity: "info" | "warning" | "critical"; title: string; detail: string; amount?: number; account?: string; date?: string; status: "unread" | "read" | "dismissed" | "resolved"; createdAt: string; readAt: string | null; dismissedAt: string | null; resolvedAt: string | null; updatedAt: string };
export type PayeeAnalytics = { payee: string; amount: number; txCount: number };
export type AccountAnalytics = { account: string; alias?: string | null; label?: string; amount: number; txCount: number };
export type ExpenseCategoryAnalytics = { account: string; alias?: string | null; label: string; amount: number; txCount: number; share: number | null; previousAmount: number; changeRatio: number | null; topPayees: PayeeAnalytics[] };
export type IncomeStatementCache = { income: IncomeStatementNode[]; expense: IncomeStatementNode[]; totalIncome: number; totalExpense: number; netIncome: number; valuationCurrency?: string; expenseAnalytics?: ExpenseCategoryAnalytics[]; topPayees?: PayeeAnalytics[]; topPaymentAccounts?: AccountAnalytics[] } | null;
export type LedgerVersion = { version?: string; signature?: string; fileCount: number; latestMtimeMs: number; totalSize?: number };
export type NetWorthPoint = { date: string; assets: number; liabilities: number; netWorth: number };
export type NetWorthDelta = { baseline: NetWorthPoint | null; change: number | null; changeRatio: number | null };
export type NetWorthWindows = { latest: NetWorthPoint | null; previousMonthEnd: NetWorthPoint | null; monthChange: number | null; sixMonth: NetWorthDelta; twelveMonth: NetWorthDelta };
export type CreditCardAnalytics = { account: string; alias?: string | null; label: string; balance: number; outstanding: number; periodSpend: number; periodRepayments: number; billCycleSpend: number; billCycleStart: string; billCycleEnd: string; statementDate: string; dueDate: string; txCount: number; repaymentCount: number; lastActivityDate: string | null };
export type CommodityPrice = { date: string; commodity: string; amount: number; currency: string };
export type InvestmentLot = { date: string; account: string; accountLabel: string; commodity: string; commodityName: string; quantity: number; unitCost?: number; costValue?: number; costCurrency?: string };
export type InvestmentPosition = { account: string; accountLabel: string; commodity: string; commodityName: string; quantity: number; latestPrice?: CommodityPrice; averageCost?: number; costValue?: number; costCurrency?: string; costValueCny?: number; marketValue?: number; marketCurrency?: string; marketValueCny?: number; lots?: InvestmentLot[] | null };
export type InvestmentQuote = { commodity: string; commodityName: string; latestPrice?: CommodityPrice; marketCurrency?: string; marketValueCny?: number; positionCount: number; positionQuantity: number };
export type InvestmentHolding = { commodity: string; commodityName: string; latestPrice?: CommodityPrice; priceHistory?: CommodityPrice[] | null; totalQuantity: number; averageCost?: number; totalCostValue?: number; costCurrency?: string; totalCostValueCny?: number; totalMarketValue?: number; marketCurrency?: string; totalMarketValueCny?: number; accountCount: number; positions?: InvestmentPosition[] | null; lots?: InvestmentLot[] | null };
export type InvestmentSummary = { totalMarketValueCny: number; holdings?: InvestmentHolding[]; positions: InvestmentPosition[]; lots?: InvestmentLot[] | null; quotes: InvestmentQuote[]; updatedAt?: string };
export type DashboardKPI = { assets: number; liabilities: number; netWorth: number; income: number; expense: number; net: number; savingsRate: number | null };
export type DashboardFilters = { categories?: string[]; accounts?: string[]; payees?: string[]; tags?: string[]; types?: ("expense" | "income" | "transfer")[]; minAmount?: number; maxAmount?: number };
export type DashboardFilterOption = { value: string; alias?: string | null; label: string; count: number };
export type DashboardFilterOptions = { categories: DashboardFilterOption[]; accounts: DashboardFilterOption[]; payees: DashboardFilterOption[]; tags: DashboardFilterOption[] };
export type DashboardAnnotation = { date: string; kind: string; label: string; payee?: string; account?: string; amount?: number; bucket?: string; severity: "info" | "warning" | "critical"; drilldown: string };
export type DashboardCashflowPoint = { month: string; income: number; expense: number; net: number };
export type DashboardSeriesPoint = { month: string; value: number };
export type DashboardDailyExpense = { date: string; weekday: string; amount: number; txCount: number };
export type DashboardWeekdayExpense = { weekday: string; amount: number; txCount: number };
export type DashboardCategorySeries = { account: string; alias?: string | null; label: string; total: number; values: DashboardSeriesPoint[] };
export type DashboardAccountSeries = { account: string; alias?: string | null; label: string; group: string; values: DashboardSeriesPoint[] };
export type DashboardAnomaly = { date: string; payee: string; narration: string; account: string; amount: number; source: string };
export type DashboardSummary = { start: string; end: string; currency: string; kpis: DashboardKPI; netWorthSeries: NetWorthPoint[]; cashflowSeries: DashboardCashflowPoint[]; dailyExpenseSeries: DashboardDailyExpense[]; weekdayExpense: DashboardWeekdayExpense[]; categorySeries: DashboardCategorySeries[]; accountBalanceSeries: DashboardAccountSeries[]; anomalies: DashboardAnomaly[]; topPayees: PayeeAnalytics[]; topPaymentAccounts: AccountAnalytics[]; filters: DashboardFilters; filterOptions: DashboardFilterOptions; annotations: DashboardAnnotation[]; generatedAt: string };
export type LedgerCache = { summary: Summary | null; balances: Record<string, number>; accountBalances?: AccountBalance[]; txns: Txn[]; netWorthRows: NetWorthPoint[]; monthEndNetWorthRows?: NetWorthPoint[]; netWorthWindows?: NetWorthWindows | null; creditCards?: CreditCardAnalytics[]; investments?: InvestmentSummary | null; reconciliationRows: ReconcileRow[]; accounts: AccountView[]; commodities?: string[]; prices?: Price[]; valuationCurrency?: string; notifications?: LedgerNotification[]; incomeStatement: IncomeStatementCache; accountStatuses: AccountStatus[]; ledgerVersion?: LedgerVersion; savedAt: number };
export type ManualKind = "expense" | "income" | "transfer";
export type ManualForm = { kind: ManualKind; date: string; payee: string; narration: string; amount: string; fromAccount: string; toAccount: string; category: string };
export type LedgerPage = "home" | "dashboard" | "net-worth" | "investments" | "transactions" | "accounts" | "imports" | "editor" | "reconcile" | "settings" | "income-statement" | "currencies";
export type LedgerNavHref = "/" | "/dashboard" | "/transactions" | "/accounts" | "/imports" | "/editor" | "/net-worth" | "/investments" | "/income-statement" | "/currencies" | "/reconcile" | "/settings";
export type PrivacySettings = { showHomeSummaryAmounts: boolean; showAccountBalancesByDefault: boolean; showNetWorthByDefault: boolean; showIncomeStatementByDefault: boolean; valuationCurrency: string };
export type ThemeMode = "system" | "light" | "dark";
export type ResolvedTheme = "light" | "dark";
export type IncomeStatementNode = { account: string; alias?: string | null; label: string; amount: number; children: IncomeStatementNode[]; depth: number; txCount: number };
