// Code generated by ent, DO NOT EDIT.

package agentsessionmessage

import (
	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContainsFold(FieldID, id))
}

// SessionKey applies equality check predicate on the "session_key" field. It's identical to SessionKeyEQ.
func SessionKey(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldSessionKey, v))
}

// Ordinal applies equality check predicate on the "ordinal" field. It's identical to OrdinalEQ.
func Ordinal(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldOrdinal, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldRole, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldContent, v))
}

// ToolCallID applies equality check predicate on the "tool_call_id" field. It's identical to ToolCallIDEQ.
func ToolCallID(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldToolCallID, v))
}

// SessionKeyEQ applies the EQ predicate on the "session_key" field.
func SessionKeyEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldSessionKey, v))
}

// SessionKeyNEQ applies the NEQ predicate on the "session_key" field.
func SessionKeyNEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldSessionKey, v))
}

// SessionKeyIn applies the In predicate on the "session_key" field.
func SessionKeyIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldSessionKey, vs...))
}

// SessionKeyNotIn applies the NotIn predicate on the "session_key" field.
func SessionKeyNotIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldSessionKey, vs...))
}

// SessionKeyGT applies the GT predicate on the "session_key" field.
func SessionKeyGT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldSessionKey, v))
}

// SessionKeyGTE applies the GTE predicate on the "session_key" field.
func SessionKeyGTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldSessionKey, v))
}

// SessionKeyLT applies the LT predicate on the "session_key" field.
func SessionKeyLT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldSessionKey, v))
}

// SessionKeyLTE applies the LTE predicate on the "session_key" field.
func SessionKeyLTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldSessionKey, v))
}

// SessionKeyContains applies the Contains predicate on the "session_key" field.
func SessionKeyContains(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContains(FieldSessionKey, v))
}

// SessionKeyHasPrefix applies the HasPrefix predicate on the "session_key" field.
func SessionKeyHasPrefix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasPrefix(FieldSessionKey, v))
}

// SessionKeyHasSuffix applies the HasSuffix predicate on the "session_key" field.
func SessionKeyHasSuffix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasSuffix(FieldSessionKey, v))
}

// SessionKeyEqualFold applies the EqualFold predicate on the "session_key" field.
func SessionKeyEqualFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEqualFold(FieldSessionKey, v))
}

// SessionKeyContainsFold applies the ContainsFold predicate on the "session_key" field.
func SessionKeyContainsFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContainsFold(FieldSessionKey, v))
}

// OrdinalEQ applies the EQ predicate on the "ordinal" field.
func OrdinalEQ(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldOrdinal, v))
}

// OrdinalNEQ applies the NEQ predicate on the "ordinal" field.
func OrdinalNEQ(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldOrdinal, v))
}

// OrdinalIn applies the In predicate on the "ordinal" field.
func OrdinalIn(vs ...int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldOrdinal, vs...))
}

// OrdinalNotIn applies the NotIn predicate on the "ordinal" field.
func OrdinalNotIn(vs ...int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldOrdinal, vs...))
}

// OrdinalGT applies the GT predicate on the "ordinal" field.
func OrdinalGT(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldOrdinal, v))
}

// OrdinalGTE applies the GTE predicate on the "ordinal" field.
func OrdinalGTE(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldOrdinal, v))
}

// OrdinalLT applies the LT predicate on the "ordinal" field.
func OrdinalLT(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldOrdinal, v))
}

// OrdinalLTE applies the LTE predicate on the "ordinal" field.
func OrdinalLTE(v int) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldOrdinal, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContainsFold(FieldRole, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContainsFold(FieldContent, v))
}

// ToolCallIDEQ applies the EQ predicate on the "tool_call_id" field.
func ToolCallIDEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEQ(FieldToolCallID, v))
}

// ToolCallIDNEQ applies the NEQ predicate on the "tool_call_id" field.
func ToolCallIDNEQ(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNEQ(FieldToolCallID, v))
}

// ToolCallIDIn applies the In predicate on the "tool_call_id" field.
func ToolCallIDIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIn(FieldToolCallID, vs...))
}

// ToolCallIDNotIn applies the NotIn predicate on the "tool_call_id" field.
func ToolCallIDNotIn(vs ...string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotIn(FieldToolCallID, vs...))
}

// ToolCallIDGT applies the GT predicate on the "tool_call_id" field.
func ToolCallIDGT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGT(FieldToolCallID, v))
}

// ToolCallIDGTE applies the GTE predicate on the "tool_call_id" field.
func ToolCallIDGTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldGTE(FieldToolCallID, v))
}

// ToolCallIDLT applies the LT predicate on the "tool_call_id" field.
func ToolCallIDLT(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLT(FieldToolCallID, v))
}

// ToolCallIDLTE applies the LTE predicate on the "tool_call_id" field.
func ToolCallIDLTE(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldLTE(FieldToolCallID, v))
}

// ToolCallIDContains applies the Contains predicate on the "tool_call_id" field.
func ToolCallIDContains(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContains(FieldToolCallID, v))
}

// ToolCallIDHasPrefix applies the HasPrefix predicate on the "tool_call_id" field.
func ToolCallIDHasPrefix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasPrefix(FieldToolCallID, v))
}

// ToolCallIDHasSuffix applies the HasSuffix predicate on the "tool_call_id" field.
func ToolCallIDHasSuffix(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldHasSuffix(FieldToolCallID, v))
}

// ToolCallIDIsNil applies the IsNil predicate on the "tool_call_id" field.
func ToolCallIDIsNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIsNull(FieldToolCallID))
}

// ToolCallIDNotNil applies the NotNil predicate on the "tool_call_id" field.
func ToolCallIDNotNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotNull(FieldToolCallID))
}

// ToolCallIDEqualFold applies the EqualFold predicate on the "tool_call_id" field.
func ToolCallIDEqualFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldEqualFold(FieldToolCallID, v))
}

// ToolCallIDContainsFold applies the ContainsFold predicate on the "tool_call_id" field.
func ToolCallIDContainsFold(v string) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldContainsFold(FieldToolCallID, v))
}

// ToolCallsIsNil applies the IsNil predicate on the "tool_calls" field.
func ToolCallsIsNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldIsNull(FieldToolCalls))
}

// ToolCallsNotNil applies the NotNil predicate on the "tool_calls" field.
func ToolCallsNotNil() predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.FieldNotNull(FieldToolCalls))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentSessionMessage) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentSessionMessage) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentSessionMessage) predicate.AgentSessionMessage {
	return predicate.AgentSessionMessage(sql.NotPredicates(p))
}
