// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/bqlhistoryrecord"
)

// BQLHistoryRecordCreate is the builder for creating a BQLHistoryRecord entity.
type BQLHistoryRecordCreate struct {
	config
	mutation *BQLHistoryRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetClusterID sets the "cluster_id" field.
func (_c *BQLHistoryRecordCreate) SetClusterID(v string) *BQLHistoryRecordCreate {
	_c.mutation.SetClusterID(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *BQLHistoryRecordCreate) SetQuery(v string) *BQLHistoryRecordCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *BQLHistoryRecordCreate) SetTitle(v string) *BQLHistoryRecordCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetTitleSource sets the "title_source" field.
func (_c *BQLHistoryRecordCreate) SetTitleSource(v string) *BQLHistoryRecordCreate {
	_c.mutation.SetTitleSource(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BQLHistoryRecordCreate) SetCreatedAt(v time.Time) *BQLHistoryRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *BQLHistoryRecordCreate) SetLastRunAt(v time.Time) *BQLHistoryRecordCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetRunCount sets the "run_count" field.
func (_c *BQLHistoryRecordCreate) SetRunCount(v int) *BQLHistoryRecordCreate {
	_c.mutation.SetRunCount(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BQLHistoryRecordCreate) SetID(v string) *BQLHistoryRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BQLHistoryRecordMutation object of the builder.
func (_c *BQLHistoryRecordCreate) Mutation() *BQLHistoryRecordMutation {
	return _c.mutation
}

// Save creates the BQLHistoryRecord in the database.
func (_c *BQLHistoryRecordCreate) Save(ctx context.Context) (*BQLHistoryRecord, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BQLHistoryRecordCreate) SaveX(ctx context.Context) *BQLHistoryRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BQLHistoryRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BQLHistoryRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BQLHistoryRecordCreate) check() error {
	if _, ok := _c.mutation.ClusterID(); !ok {
		return &ValidationError{Name: "cluster_id", err: errors.New(`ent: missing required field "BQLHistoryRecord.cluster_id"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "BQLHistoryRecord.query"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "BQLHistoryRecord.title"`)}
	}
	if _, ok := _c.mutation.TitleSource(); !ok {
		return &ValidationError{Name: "title_source", err: errors.New(`ent: missing required field "BQLHistoryRecord.title_source"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BQLHistoryRecord.created_at"`)}
	}
	if _, ok := _c.mutation.LastRunAt(); !ok {
		return &ValidationError{Name: "last_run_at", err: errors.New(`ent: missing required field "BQLHistoryRecord.last_run_at"`)}
	}
	if _, ok := _c.mutation.RunCount(); !ok {
		return &ValidationError{Name: "run_count", err: errors.New(`ent: missing required field "BQLHistoryRecord.run_count"`)}
	}
	return nil
}

func (_c *BQLHistoryRecordCreate) sqlSave(ctx context.Context) (*BQLHistoryRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BQLHistoryRecord.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BQLHistoryRecordCreate) createSpec() (*BQLHistoryRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &BQLHistoryRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bqlhistoryrecord.Table, sqlgraph.NewFieldSpec(bqlhistoryrecord.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClusterID(); ok {
		_spec.SetField(bqlhistoryrecord.FieldClusterID, field.TypeString, value)
		_node.ClusterID = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(bqlhistoryrecord.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(bqlhistoryrecord.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.TitleSource(); ok {
		_spec.SetField(bqlhistoryrecord.FieldTitleSource, field.TypeString, value)
		_node.TitleSource = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bqlhistoryrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(bqlhistoryrecord.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = value
	}
	if value, ok := _c.mutation.RunCount(); ok {
		_spec.SetField(bqlhistoryrecord.FieldRunCount, field.TypeInt, value)
		_node.RunCount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BQLHistoryRecord.Create().
//		SetClusterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BQLHistoryRecordUpsert) {
//			SetClusterID(v+v).
//		}).
//		Exec(ctx)
func (_c *BQLHistoryRecordCreate) OnConflict(opts ...sql.ConflictOption) *BQLHistoryRecordUpsertOne {
	_c.conflict = opts
	return &BQLHistoryRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BQLHistoryRecordCreate) OnConflictColumns(columns ...string) *BQLHistoryRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BQLHistoryRecordUpsertOne{
		create: _c,
	}
}

type (
	// BQLHistoryRecordUpsertOne is the builder for "upsert"-ing
	//  one BQLHistoryRecord node.
	BQLHistoryRecordUpsertOne struct {
		create *BQLHistoryRecordCreate
	}

	// BQLHistoryRecordUpsert is the "OnConflict" setter.
	BQLHistoryRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuery sets the "query" field.
func (u *BQLHistoryRecordUpsert) SetQuery(v string) *BQLHistoryRecordUpsert {
	u.Set(bqlhistoryrecord.FieldQuery, v)
	return u
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsert) UpdateQuery() *BQLHistoryRecordUpsert {
	u.SetExcluded(bqlhistoryrecord.FieldQuery)
	return u
}

// SetTitle sets the "title" field.
func (u *BQLHistoryRecordUpsert) SetTitle(v string) *BQLHistoryRecordUpsert {
	u.Set(bqlhistoryrecord.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsert) UpdateTitle() *BQLHistoryRecordUpsert {
	u.SetExcluded(bqlhistoryrecord.FieldTitle)
	return u
}

// SetTitleSource sets the "title_source" field.
func (u *BQLHistoryRecordUpsert) SetTitleSource(v string) *BQLHistoryRecordUpsert {
	u.Set(bqlhistoryrecord.FieldTitleSource, v)
	return u
}

// UpdateTitleSource sets the "title_source" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsert) UpdateTitleSource() *BQLHistoryRecordUpsert {
	u.SetExcluded(bqlhistoryrecord.FieldTitleSource)
	return u
}

// SetLastRunAt sets the "last_run_at" field.
func (u *BQLHistoryRecordUpsert) SetLastRunAt(v time.Time) *BQLHistoryRecordUpsert {
	u.Set(bqlhistoryrecord.FieldLastRunAt, v)
	return u
}

// UpdateLastRunAt sets the "last_run_at" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsert) UpdateLastRunAt() *BQLHistoryRecordUpsert {
	u.SetExcluded(bqlhistoryrecord.FieldLastRunAt)
	return u
}

// SetRunCount sets the "run_count" field.
func (u *BQLHistoryRecordUpsert) SetRunCount(v int) *BQLHistoryRecordUpsert {
	u.Set(bqlhistoryrecord.FieldRunCount, v)
	return u
}

// UpdateRunCount sets the "run_count" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsert) UpdateRunCount() *BQLHistoryRecordUpsert {
	u.SetExcluded(bqlhistoryrecord.FieldRunCount)
	return u
}

// AddRunCount adds v to the "run_count" field.
func (u *BQLHistoryRecordUpsert) AddRunCount(v int) *BQLHistoryRecordUpsert {
	u.Add(bqlhistoryrecord.FieldRunCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bqlhistoryrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BQLHistoryRecordUpsertOne) UpdateNewValues() *BQLHistoryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(bqlhistoryrecord.FieldID)
		}
		if _, exists := u.create.mutation.ClusterID(); exists {
			s.SetIgnore(bqlhistoryrecord.FieldClusterID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(bqlhistoryrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BQLHistoryRecordUpsertOne) Ignore() *BQLHistoryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BQLHistoryRecordUpsertOne) DoNothing() *BQLHistoryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BQLHistoryRecordCreate.OnConflict
// documentation for more info.
func (u *BQLHistoryRecordUpsertOne) Update(set func(*BQLHistoryRecordUpsert)) *BQLHistoryRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BQLHistoryRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuery sets the "query" field.
func (u *BQLHistoryRecordUpsertOne) SetQuery(v string) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertOne) UpdateQuery() *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateQuery()
	})
}

// SetTitle sets the "title" field.
func (u *BQLHistoryRecordUpsertOne) SetTitle(v string) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertOne) UpdateTitle() *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateTitle()
	})
}

// SetTitleSource sets the "title_source" field.
func (u *BQLHistoryRecordUpsertOne) SetTitleSource(v string) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetTitleSource(v)
	})
}

// UpdateTitleSource sets the "title_source" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertOne) UpdateTitleSource() *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateTitleSource()
	})
}

// SetLastRunAt sets the "last_run_at" field.
func (u *BQLHistoryRecordUpsertOne) SetLastRunAt(v time.Time) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetLastRunAt(v)
	})
}

// UpdateLastRunAt sets the "last_run_at" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertOne) UpdateLastRunAt() *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateLastRunAt()
	})
}

// SetRunCount sets the "run_count" field.
func (u *BQLHistoryRecordUpsertOne) SetRunCount(v int) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetRunCount(v)
	})
}

// AddRunCount adds v to the "run_count" field.
func (u *BQLHistoryRecordUpsertOne) AddRunCount(v int) *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.AddRunCount(v)
	})
}

// UpdateRunCount sets the "run_count" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertOne) UpdateRunCount() *BQLHistoryRecordUpsertOne {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateRunCount()
	})
}

// Exec executes the query.
func (u *BQLHistoryRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BQLHistoryRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BQLHistoryRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BQLHistoryRecordUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BQLHistoryRecordUpsertOne.ID is not supported by MySQL driver. Use BQLHistoryRecordUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BQLHistoryRecordUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BQLHistoryRecordCreateBulk is the builder for creating many BQLHistoryRecord entities in bulk.
type BQLHistoryRecordCreateBulk struct {
	config
	err      error
	builders []*BQLHistoryRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the BQLHistoryRecord entities in the database.
func (_c *BQLHistoryRecordCreateBulk) Save(ctx context.Context) ([]*BQLHistoryRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BQLHistoryRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BQLHistoryRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BQLHistoryRecordCreateBulk) SaveX(ctx context.Context) []*BQLHistoryRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BQLHistoryRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BQLHistoryRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BQLHistoryRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BQLHistoryRecordUpsert) {
//			SetClusterID(v+v).
//		}).
//		Exec(ctx)
func (_c *BQLHistoryRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *BQLHistoryRecordUpsertBulk {
	_c.conflict = opts
	return &BQLHistoryRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BQLHistoryRecordCreateBulk) OnConflictColumns(columns ...string) *BQLHistoryRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BQLHistoryRecordUpsertBulk{
		create: _c,
	}
}

// BQLHistoryRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of BQLHistoryRecord nodes.
type BQLHistoryRecordUpsertBulk struct {
	create *BQLHistoryRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bqlhistoryrecord.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BQLHistoryRecordUpsertBulk) UpdateNewValues() *BQLHistoryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(bqlhistoryrecord.FieldID)
			}
			if _, exists := b.mutation.ClusterID(); exists {
				s.SetIgnore(bqlhistoryrecord.FieldClusterID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(bqlhistoryrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BQLHistoryRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BQLHistoryRecordUpsertBulk) Ignore() *BQLHistoryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BQLHistoryRecordUpsertBulk) DoNothing() *BQLHistoryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BQLHistoryRecordCreateBulk.OnConflict
// documentation for more info.
func (u *BQLHistoryRecordUpsertBulk) Update(set func(*BQLHistoryRecordUpsert)) *BQLHistoryRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BQLHistoryRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuery sets the "query" field.
func (u *BQLHistoryRecordUpsertBulk) SetQuery(v string) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertBulk) UpdateQuery() *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateQuery()
	})
}

// SetTitle sets the "title" field.
func (u *BQLHistoryRecordUpsertBulk) SetTitle(v string) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertBulk) UpdateTitle() *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateTitle()
	})
}

// SetTitleSource sets the "title_source" field.
func (u *BQLHistoryRecordUpsertBulk) SetTitleSource(v string) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetTitleSource(v)
	})
}

// UpdateTitleSource sets the "title_source" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertBulk) UpdateTitleSource() *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateTitleSource()
	})
}

// SetLastRunAt sets the "last_run_at" field.
func (u *BQLHistoryRecordUpsertBulk) SetLastRunAt(v time.Time) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetLastRunAt(v)
	})
}

// UpdateLastRunAt sets the "last_run_at" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertBulk) UpdateLastRunAt() *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateLastRunAt()
	})
}

// SetRunCount sets the "run_count" field.
func (u *BQLHistoryRecordUpsertBulk) SetRunCount(v int) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.SetRunCount(v)
	})
}

// AddRunCount adds v to the "run_count" field.
func (u *BQLHistoryRecordUpsertBulk) AddRunCount(v int) *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.AddRunCount(v)
	})
}

// UpdateRunCount sets the "run_count" field to the value that was provided on create.
func (u *BQLHistoryRecordUpsertBulk) UpdateRunCount() *BQLHistoryRecordUpsertBulk {
	return u.Update(func(s *BQLHistoryRecordUpsert) {
		s.UpdateRunCount()
	})
}

// Exec executes the query.
func (u *BQLHistoryRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BQLHistoryRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BQLHistoryRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BQLHistoryRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
