// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/bqlhistoryrecord"
)

// BQLHistoryRecord is the model entity for the BQLHistoryRecord schema.
type BQLHistoryRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ClusterID holds the value of the "cluster_id" field.
	ClusterID string `json:"cluster_id,omitempty"`
	// Query holds the value of the "query" field.
	Query string `json:"query,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// TitleSource holds the value of the "title_source" field.
	TitleSource string `json:"title_source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastRunAt holds the value of the "last_run_at" field.
	LastRunAt time.Time `json:"last_run_at,omitempty"`
	// RunCount holds the value of the "run_count" field.
	RunCount     int `json:"run_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BQLHistoryRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bqlhistoryrecord.FieldRunCount:
			values[i] = new(sql.NullInt64)
		case bqlhistoryrecord.FieldID, bqlhistoryrecord.FieldClusterID, bqlhistoryrecord.FieldQuery, bqlhistoryrecord.FieldTitle, bqlhistoryrecord.FieldTitleSource:
			values[i] = new(sql.NullString)
		case bqlhistoryrecord.FieldCreatedAt, bqlhistoryrecord.FieldLastRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BQLHistoryRecord fields.
func (_m *BQLHistoryRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bqlhistoryrecord.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case bqlhistoryrecord.FieldClusterID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cluster_id", values[i])
			} else if value.Valid {
				_m.ClusterID = value.String
			}
		case bqlhistoryrecord.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				_m.Query = value.String
			}
		case bqlhistoryrecord.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case bqlhistoryrecord.FieldTitleSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_source", values[i])
			} else if value.Valid {
				_m.TitleSource = value.String
			}
		case bqlhistoryrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bqlhistoryrecord.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = value.Time
			}
		case bqlhistoryrecord.FieldRunCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_count", values[i])
			} else if value.Valid {
				_m.RunCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BQLHistoryRecord.
// This includes values selected through modifiers, order, etc.
func (_m *BQLHistoryRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BQLHistoryRecord.
// Note that you need to call BQLHistoryRecord.Unwrap() before calling this method if this BQLHistoryRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BQLHistoryRecord) Update() *BQLHistoryRecordUpdateOne {
	return NewBQLHistoryRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BQLHistoryRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BQLHistoryRecord) Unwrap() *BQLHistoryRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BQLHistoryRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BQLHistoryRecord) String() string {
	var builder strings.Builder
	builder.WriteString("BQLHistoryRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cluster_id=")
	builder.WriteString(_m.ClusterID)
	builder.WriteString(", ")
	builder.WriteString("query=")
	builder.WriteString(_m.Query)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("title_source=")
	builder.WriteString(_m.TitleSource)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_run_at=")
	builder.WriteString(_m.LastRunAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("run_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunCount))
	builder.WriteByte(')')
	return builder.String()
}

// BQLHistoryRecords is a parsable slice of BQLHistoryRecord.
type BQLHistoryRecords []*BQLHistoryRecord
