// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/gmailpendingimport"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// GmailPendingImportUpdate is the builder for updating GmailPendingImport entities.
type GmailPendingImportUpdate struct {
	config
	hooks    []Hook
	mutation *GmailPendingImportMutation
}

// Where appends a list predicates to the GmailPendingImportUpdate builder.
func (_u *GmailPendingImportUpdate) Where(ps ...predicate.GmailPendingImport) *GmailPendingImportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetImportID sets the "import_id" field.
func (_u *GmailPendingImportUpdate) SetImportID(v string) *GmailPendingImportUpdate {
	_u.mutation.SetImportID(v)
	return _u
}

// SetNillableImportID sets the "import_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableImportID(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetImportID(*v)
	}
	return _u
}

// ClearImportID clears the value of the "import_id" field.
func (_u *GmailPendingImportUpdate) ClearImportID() *GmailPendingImportUpdate {
	_u.mutation.ClearImportID()
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *GmailPendingImportUpdate) SetSourceKey(v string) *GmailPendingImportUpdate {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableSourceKey(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// ClearSourceKey clears the value of the "source_key" field.
func (_u *GmailPendingImportUpdate) ClearSourceKey() *GmailPendingImportUpdate {
	_u.mutation.ClearSourceKey()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *GmailPendingImportUpdate) SetMessageID(v string) *GmailPendingImportUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableMessageID(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *GmailPendingImportUpdate) SetThreadID(v string) *GmailPendingImportUpdate {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableThreadID(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *GmailPendingImportUpdate) ClearThreadID() *GmailPendingImportUpdate {
	_u.mutation.ClearThreadID()
	return _u
}

// SetSender sets the "sender" field.
func (_u *GmailPendingImportUpdate) SetSender(v string) *GmailPendingImportUpdate {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableSender(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *GmailPendingImportUpdate) SetSubject(v string) *GmailPendingImportUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableSubject(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *GmailPendingImportUpdate) SetReceivedAt(v time.Time) *GmailPendingImportUpdate {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableReceivedAt(v *time.Time) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// ClearReceivedAt clears the value of the "received_at" field.
func (_u *GmailPendingImportUpdate) ClearReceivedAt() *GmailPendingImportUpdate {
	_u.mutation.ClearReceivedAt()
	return _u
}

// SetFilename sets the "filename" field.
func (_u *GmailPendingImportUpdate) SetFilename(v string) *GmailPendingImportUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableFilename(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *GmailPendingImportUpdate) SetProvider(v string) *GmailPendingImportUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableProvider(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *GmailPendingImportUpdate) ClearProvider() *GmailPendingImportUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *GmailPendingImportUpdate) SetCandidateCount(v int) *GmailPendingImportUpdate {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableCandidateCount(v *int) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *GmailPendingImportUpdate) AddCandidateCount(v int) *GmailPendingImportUpdate {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GmailPendingImportUpdate) SetStatus(v string) *GmailPendingImportUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableStatus(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *GmailPendingImportUpdate) SetError(v string) *GmailPendingImportUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableError(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *GmailPendingImportUpdate) ClearError() *GmailPendingImportUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GmailPendingImportUpdate) SetUpdatedAt(v time.Time) *GmailPendingImportUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableUpdatedAt(v *time.Time) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetStoredBytes sets the "stored_bytes" field.
func (_u *GmailPendingImportUpdate) SetStoredBytes(v int64) *GmailPendingImportUpdate {
	_u.mutation.ResetStoredBytes()
	_u.mutation.SetStoredBytes(v)
	return _u
}

// SetNillableStoredBytes sets the "stored_bytes" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableStoredBytes(v *int64) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetStoredBytes(*v)
	}
	return _u
}

// AddStoredBytes adds value to the "stored_bytes" field.
func (_u *GmailPendingImportUpdate) AddStoredBytes(v int64) *GmailPendingImportUpdate {
	_u.mutation.AddStoredBytes(v)
	return _u
}

// SetOutputFile sets the "output_file" field.
func (_u *GmailPendingImportUpdate) SetOutputFile(v string) *GmailPendingImportUpdate {
	_u.mutation.SetOutputFile(v)
	return _u
}

// SetNillableOutputFile sets the "output_file" field if the given value is not nil.
func (_u *GmailPendingImportUpdate) SetNillableOutputFile(v *string) *GmailPendingImportUpdate {
	if v != nil {
		_u.SetOutputFile(*v)
	}
	return _u
}

// ClearOutputFile clears the value of the "output_file" field.
func (_u *GmailPendingImportUpdate) ClearOutputFile() *GmailPendingImportUpdate {
	_u.mutation.ClearOutputFile()
	return _u
}

// Mutation returns the GmailPendingImportMutation object of the builder.
func (_u *GmailPendingImportUpdate) Mutation() *GmailPendingImportMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GmailPendingImportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GmailPendingImportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GmailPendingImportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GmailPendingImportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GmailPendingImportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(gmailpendingimport.Table, gmailpendingimport.Columns, sqlgraph.NewFieldSpec(gmailpendingimport.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImportID(); ok {
		_spec.SetField(gmailpendingimport.FieldImportID, field.TypeString, value)
	}
	if _u.mutation.ImportIDCleared() {
		_spec.ClearField(gmailpendingimport.FieldImportID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(gmailpendingimport.FieldSourceKey, field.TypeString, value)
	}
	if _u.mutation.SourceKeyCleared() {
		_spec.ClearField(gmailpendingimport.FieldSourceKey, field.TypeString)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(gmailpendingimport.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(gmailpendingimport.FieldThreadID, field.TypeString, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(gmailpendingimport.FieldThreadID, field.TypeString)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(gmailpendingimport.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(gmailpendingimport.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(gmailpendingimport.FieldReceivedAt, field.TypeTime, value)
	}
	if _u.mutation.ReceivedAtCleared() {
		_spec.ClearField(gmailpendingimport.FieldReceivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(gmailpendingimport.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(gmailpendingimport.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(gmailpendingimport.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(gmailpendingimport.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(gmailpendingimport.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gmailpendingimport.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(gmailpendingimport.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(gmailpendingimport.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gmailpendingimport.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StoredBytes(); ok {
		_spec.SetField(gmailpendingimport.FieldStoredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoredBytes(); ok {
		_spec.AddField(gmailpendingimport.FieldStoredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputFile(); ok {
		_spec.SetField(gmailpendingimport.FieldOutputFile, field.TypeString, value)
	}
	if _u.mutation.OutputFileCleared() {
		_spec.ClearField(gmailpendingimport.FieldOutputFile, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gmailpendingimport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GmailPendingImportUpdateOne is the builder for updating a single GmailPendingImport entity.
type GmailPendingImportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GmailPendingImportMutation
}

// SetImportID sets the "import_id" field.
func (_u *GmailPendingImportUpdateOne) SetImportID(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetImportID(v)
	return _u
}

// SetNillableImportID sets the "import_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableImportID(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetImportID(*v)
	}
	return _u
}

// ClearImportID clears the value of the "import_id" field.
func (_u *GmailPendingImportUpdateOne) ClearImportID() *GmailPendingImportUpdateOne {
	_u.mutation.ClearImportID()
	return _u
}

// SetSourceKey sets the "source_key" field.
func (_u *GmailPendingImportUpdateOne) SetSourceKey(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetSourceKey(v)
	return _u
}

// SetNillableSourceKey sets the "source_key" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableSourceKey(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetSourceKey(*v)
	}
	return _u
}

// ClearSourceKey clears the value of the "source_key" field.
func (_u *GmailPendingImportUpdateOne) ClearSourceKey() *GmailPendingImportUpdateOne {
	_u.mutation.ClearSourceKey()
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *GmailPendingImportUpdateOne) SetMessageID(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableMessageID(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetThreadID sets the "thread_id" field.
func (_u *GmailPendingImportUpdateOne) SetThreadID(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetThreadID(v)
	return _u
}

// SetNillableThreadID sets the "thread_id" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableThreadID(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetThreadID(*v)
	}
	return _u
}

// ClearThreadID clears the value of the "thread_id" field.
func (_u *GmailPendingImportUpdateOne) ClearThreadID() *GmailPendingImportUpdateOne {
	_u.mutation.ClearThreadID()
	return _u
}

// SetSender sets the "sender" field.
func (_u *GmailPendingImportUpdateOne) SetSender(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableSender(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *GmailPendingImportUpdateOne) SetSubject(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableSubject(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *GmailPendingImportUpdateOne) SetReceivedAt(v time.Time) *GmailPendingImportUpdateOne {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableReceivedAt(v *time.Time) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// ClearReceivedAt clears the value of the "received_at" field.
func (_u *GmailPendingImportUpdateOne) ClearReceivedAt() *GmailPendingImportUpdateOne {
	_u.mutation.ClearReceivedAt()
	return _u
}

// SetFilename sets the "filename" field.
func (_u *GmailPendingImportUpdateOne) SetFilename(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableFilename(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *GmailPendingImportUpdateOne) SetProvider(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableProvider(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *GmailPendingImportUpdateOne) ClearProvider() *GmailPendingImportUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetCandidateCount sets the "candidate_count" field.
func (_u *GmailPendingImportUpdateOne) SetCandidateCount(v int) *GmailPendingImportUpdateOne {
	_u.mutation.ResetCandidateCount()
	_u.mutation.SetCandidateCount(v)
	return _u
}

// SetNillableCandidateCount sets the "candidate_count" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableCandidateCount(v *int) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetCandidateCount(*v)
	}
	return _u
}

// AddCandidateCount adds value to the "candidate_count" field.
func (_u *GmailPendingImportUpdateOne) AddCandidateCount(v int) *GmailPendingImportUpdateOne {
	_u.mutation.AddCandidateCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *GmailPendingImportUpdateOne) SetStatus(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableStatus(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *GmailPendingImportUpdateOne) SetError(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableError(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *GmailPendingImportUpdateOne) ClearError() *GmailPendingImportUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GmailPendingImportUpdateOne) SetUpdatedAt(v time.Time) *GmailPendingImportUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableUpdatedAt(v *time.Time) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetStoredBytes sets the "stored_bytes" field.
func (_u *GmailPendingImportUpdateOne) SetStoredBytes(v int64) *GmailPendingImportUpdateOne {
	_u.mutation.ResetStoredBytes()
	_u.mutation.SetStoredBytes(v)
	return _u
}

// SetNillableStoredBytes sets the "stored_bytes" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableStoredBytes(v *int64) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetStoredBytes(*v)
	}
	return _u
}

// AddStoredBytes adds value to the "stored_bytes" field.
func (_u *GmailPendingImportUpdateOne) AddStoredBytes(v int64) *GmailPendingImportUpdateOne {
	_u.mutation.AddStoredBytes(v)
	return _u
}

// SetOutputFile sets the "output_file" field.
func (_u *GmailPendingImportUpdateOne) SetOutputFile(v string) *GmailPendingImportUpdateOne {
	_u.mutation.SetOutputFile(v)
	return _u
}

// SetNillableOutputFile sets the "output_file" field if the given value is not nil.
func (_u *GmailPendingImportUpdateOne) SetNillableOutputFile(v *string) *GmailPendingImportUpdateOne {
	if v != nil {
		_u.SetOutputFile(*v)
	}
	return _u
}

// ClearOutputFile clears the value of the "output_file" field.
func (_u *GmailPendingImportUpdateOne) ClearOutputFile() *GmailPendingImportUpdateOne {
	_u.mutation.ClearOutputFile()
	return _u
}

// Mutation returns the GmailPendingImportMutation object of the builder.
func (_u *GmailPendingImportUpdateOne) Mutation() *GmailPendingImportMutation {
	return _u.mutation
}

// Where appends a list predicates to the GmailPendingImportUpdate builder.
func (_u *GmailPendingImportUpdateOne) Where(ps ...predicate.GmailPendingImport) *GmailPendingImportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GmailPendingImportUpdateOne) Select(field string, fields ...string) *GmailPendingImportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GmailPendingImport entity.
func (_u *GmailPendingImportUpdateOne) Save(ctx context.Context) (*GmailPendingImport, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GmailPendingImportUpdateOne) SaveX(ctx context.Context) *GmailPendingImport {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GmailPendingImportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GmailPendingImportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GmailPendingImportUpdateOne) sqlSave(ctx context.Context) (_node *GmailPendingImport, err error) {
	_spec := sqlgraph.NewUpdateSpec(gmailpendingimport.Table, gmailpendingimport.Columns, sqlgraph.NewFieldSpec(gmailpendingimport.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GmailPendingImport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gmailpendingimport.FieldID)
		for _, f := range fields {
			if !gmailpendingimport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gmailpendingimport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ImportID(); ok {
		_spec.SetField(gmailpendingimport.FieldImportID, field.TypeString, value)
	}
	if _u.mutation.ImportIDCleared() {
		_spec.ClearField(gmailpendingimport.FieldImportID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceKey(); ok {
		_spec.SetField(gmailpendingimport.FieldSourceKey, field.TypeString, value)
	}
	if _u.mutation.SourceKeyCleared() {
		_spec.ClearField(gmailpendingimport.FieldSourceKey, field.TypeString)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(gmailpendingimport.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThreadID(); ok {
		_spec.SetField(gmailpendingimport.FieldThreadID, field.TypeString, value)
	}
	if _u.mutation.ThreadIDCleared() {
		_spec.ClearField(gmailpendingimport.FieldThreadID, field.TypeString)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(gmailpendingimport.FieldSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(gmailpendingimport.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(gmailpendingimport.FieldReceivedAt, field.TypeTime, value)
	}
	if _u.mutation.ReceivedAtCleared() {
		_spec.ClearField(gmailpendingimport.FieldReceivedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(gmailpendingimport.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(gmailpendingimport.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(gmailpendingimport.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.CandidateCount(); ok {
		_spec.SetField(gmailpendingimport.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCandidateCount(); ok {
		_spec.AddField(gmailpendingimport.FieldCandidateCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(gmailpendingimport.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(gmailpendingimport.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(gmailpendingimport.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gmailpendingimport.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StoredBytes(); ok {
		_spec.SetField(gmailpendingimport.FieldStoredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoredBytes(); ok {
		_spec.AddField(gmailpendingimport.FieldStoredBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputFile(); ok {
		_spec.SetField(gmailpendingimport.FieldOutputFile, field.TypeString, value)
	}
	if _u.mutation.OutputFileCleared() {
		_spec.ClearField(gmailpendingimport.FieldOutputFile, field.TypeString)
	}
	_node = &GmailPendingImport{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gmailpendingimport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
