// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/gmailpushevent"
)

// GmailPushEventCreate is the builder for creating a GmailPushEvent entity.
type GmailPushEventCreate struct {
	config
	mutation *GmailPushEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEmail sets the "email" field.
func (_c *GmailPushEventCreate) SetEmail(v string) *GmailPushEventCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetHistoryID sets the "history_id" field.
func (_c *GmailPushEventCreate) SetHistoryID(v string) *GmailPushEventCreate {
	_c.mutation.SetHistoryID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GmailPushEventCreate) SetStatus(v string) *GmailPushEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *GmailPushEventCreate) SetAttempts(v int) *GmailPushEventCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *GmailPushEventCreate) SetAvailableAt(v time.Time) *GmailPushEventCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetLeaseUntil sets the "lease_until" field.
func (_c *GmailPushEventCreate) SetLeaseUntil(v time.Time) *GmailPushEventCreate {
	_c.mutation.SetLeaseUntil(v)
	return _c
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_c *GmailPushEventCreate) SetNillableLeaseUntil(v *time.Time) *GmailPushEventCreate {
	if v != nil {
		_c.SetLeaseUntil(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *GmailPushEventCreate) SetLastError(v string) *GmailPushEventCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GmailPushEventCreate) SetCreatedAt(v time.Time) *GmailPushEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GmailPushEventCreate) SetUpdatedAt(v time.Time) *GmailPushEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GmailPushEventCreate) SetID(v string) *GmailPushEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GmailPushEventMutation object of the builder.
func (_c *GmailPushEventCreate) Mutation() *GmailPushEventMutation {
	return _c.mutation
}

// Save creates the GmailPushEvent in the database.
func (_c *GmailPushEventCreate) Save(ctx context.Context) (*GmailPushEvent, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GmailPushEventCreate) SaveX(ctx context.Context) *GmailPushEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GmailPushEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GmailPushEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GmailPushEventCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "GmailPushEvent.email"`)}
	}
	if _, ok := _c.mutation.HistoryID(); !ok {
		return &ValidationError{Name: "history_id", err: errors.New(`ent: missing required field "GmailPushEvent.history_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GmailPushEvent.status"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "GmailPushEvent.attempts"`)}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "GmailPushEvent.available_at"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "GmailPushEvent.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GmailPushEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GmailPushEvent.updated_at"`)}
	}
	return nil
}

func (_c *GmailPushEventCreate) sqlSave(ctx context.Context) (*GmailPushEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GmailPushEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GmailPushEventCreate) createSpec() (*GmailPushEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GmailPushEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gmailpushevent.Table, sqlgraph.NewFieldSpec(gmailpushevent.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(gmailpushevent.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.HistoryID(); ok {
		_spec.SetField(gmailpushevent.FieldHistoryID, field.TypeString, value)
		_node.HistoryID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(gmailpushevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(gmailpushevent.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(gmailpushevent.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.LeaseUntil(); ok {
		_spec.SetField(gmailpushevent.FieldLeaseUntil, field.TypeTime, value)
		_node.LeaseUntil = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(gmailpushevent.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gmailpushevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gmailpushevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GmailPushEvent.Create().
//		SetEmail(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GmailPushEventUpsert) {
//			SetEmail(v+v).
//		}).
//		Exec(ctx)
func (_c *GmailPushEventCreate) OnConflict(opts ...sql.ConflictOption) *GmailPushEventUpsertOne {
	_c.conflict = opts
	return &GmailPushEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GmailPushEventCreate) OnConflictColumns(columns ...string) *GmailPushEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GmailPushEventUpsertOne{
		create: _c,
	}
}

type (
	// GmailPushEventUpsertOne is the builder for "upsert"-ing
	//  one GmailPushEvent node.
	GmailPushEventUpsertOne struct {
		create *GmailPushEventCreate
	}

	// GmailPushEventUpsert is the "OnConflict" setter.
	GmailPushEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetEmail sets the "email" field.
func (u *GmailPushEventUpsert) SetEmail(v string) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateEmail() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldEmail)
	return u
}

// SetHistoryID sets the "history_id" field.
func (u *GmailPushEventUpsert) SetHistoryID(v string) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldHistoryID, v)
	return u
}

// UpdateHistoryID sets the "history_id" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateHistoryID() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldHistoryID)
	return u
}

// SetStatus sets the "status" field.
func (u *GmailPushEventUpsert) SetStatus(v string) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateStatus() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldStatus)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *GmailPushEventUpsert) SetAttempts(v int) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateAttempts() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *GmailPushEventUpsert) AddAttempts(v int) *GmailPushEventUpsert {
	u.Add(gmailpushevent.FieldAttempts, v)
	return u
}

// SetAvailableAt sets the "available_at" field.
func (u *GmailPushEventUpsert) SetAvailableAt(v time.Time) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldAvailableAt, v)
	return u
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateAvailableAt() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldAvailableAt)
	return u
}

// SetLeaseUntil sets the "lease_until" field.
func (u *GmailPushEventUpsert) SetLeaseUntil(v time.Time) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldLeaseUntil, v)
	return u
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateLeaseUntil() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldLeaseUntil)
	return u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *GmailPushEventUpsert) ClearLeaseUntil() *GmailPushEventUpsert {
	u.SetNull(gmailpushevent.FieldLeaseUntil)
	return u
}

// SetLastError sets the "last_error" field.
func (u *GmailPushEventUpsert) SetLastError(v string) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateLastError() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldLastError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GmailPushEventUpsert) SetUpdatedAt(v time.Time) *GmailPushEventUpsert {
	u.Set(gmailpushevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GmailPushEventUpsert) UpdateUpdatedAt() *GmailPushEventUpsert {
	u.SetExcluded(gmailpushevent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gmailpushevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GmailPushEventUpsertOne) UpdateNewValues() *GmailPushEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(gmailpushevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(gmailpushevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GmailPushEventUpsertOne) Ignore() *GmailPushEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GmailPushEventUpsertOne) DoNothing() *GmailPushEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GmailPushEventCreate.OnConflict
// documentation for more info.
func (u *GmailPushEventUpsertOne) Update(set func(*GmailPushEventUpsert)) *GmailPushEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GmailPushEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmail sets the "email" field.
func (u *GmailPushEventUpsertOne) SetEmail(v string) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateEmail() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateEmail()
	})
}

// SetHistoryID sets the "history_id" field.
func (u *GmailPushEventUpsertOne) SetHistoryID(v string) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetHistoryID(v)
	})
}

// UpdateHistoryID sets the "history_id" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateHistoryID() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateHistoryID()
	})
}

// SetStatus sets the "status" field.
func (u *GmailPushEventUpsertOne) SetStatus(v string) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateStatus() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *GmailPushEventUpsertOne) SetAttempts(v int) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *GmailPushEventUpsertOne) AddAttempts(v int) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateAttempts() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *GmailPushEventUpsertOne) SetAvailableAt(v time.Time) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateAvailableAt() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *GmailPushEventUpsertOne) SetLeaseUntil(v time.Time) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateLeaseUntil() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *GmailPushEventUpsertOne) ClearLeaseUntil() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetLastError sets the "last_error" field.
func (u *GmailPushEventUpsertOne) SetLastError(v string) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateLastError() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GmailPushEventUpsertOne) SetUpdatedAt(v time.Time) *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GmailPushEventUpsertOne) UpdateUpdatedAt() *GmailPushEventUpsertOne {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GmailPushEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GmailPushEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GmailPushEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GmailPushEventUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GmailPushEventUpsertOne.ID is not supported by MySQL driver. Use GmailPushEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GmailPushEventUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GmailPushEventCreateBulk is the builder for creating many GmailPushEvent entities in bulk.
type GmailPushEventCreateBulk struct {
	config
	err      error
	builders []*GmailPushEventCreate
	conflict []sql.ConflictOption
}

// Save creates the GmailPushEvent entities in the database.
func (_c *GmailPushEventCreateBulk) Save(ctx context.Context) ([]*GmailPushEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GmailPushEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GmailPushEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GmailPushEventCreateBulk) SaveX(ctx context.Context) []*GmailPushEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GmailPushEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GmailPushEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GmailPushEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GmailPushEventUpsert) {
//			SetEmail(v+v).
//		}).
//		Exec(ctx)
func (_c *GmailPushEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *GmailPushEventUpsertBulk {
	_c.conflict = opts
	return &GmailPushEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GmailPushEventCreateBulk) OnConflictColumns(columns ...string) *GmailPushEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GmailPushEventUpsertBulk{
		create: _c,
	}
}

// GmailPushEventUpsertBulk is the builder for "upsert"-ing
// a bulk of GmailPushEvent nodes.
type GmailPushEventUpsertBulk struct {
	create *GmailPushEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gmailpushevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GmailPushEventUpsertBulk) UpdateNewValues() *GmailPushEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(gmailpushevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(gmailpushevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GmailPushEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GmailPushEventUpsertBulk) Ignore() *GmailPushEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GmailPushEventUpsertBulk) DoNothing() *GmailPushEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GmailPushEventCreateBulk.OnConflict
// documentation for more info.
func (u *GmailPushEventUpsertBulk) Update(set func(*GmailPushEventUpsert)) *GmailPushEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GmailPushEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEmail sets the "email" field.
func (u *GmailPushEventUpsertBulk) SetEmail(v string) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateEmail() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateEmail()
	})
}

// SetHistoryID sets the "history_id" field.
func (u *GmailPushEventUpsertBulk) SetHistoryID(v string) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetHistoryID(v)
	})
}

// UpdateHistoryID sets the "history_id" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateHistoryID() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateHistoryID()
	})
}

// SetStatus sets the "status" field.
func (u *GmailPushEventUpsertBulk) SetStatus(v string) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateStatus() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *GmailPushEventUpsertBulk) SetAttempts(v int) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *GmailPushEventUpsertBulk) AddAttempts(v int) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateAttempts() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *GmailPushEventUpsertBulk) SetAvailableAt(v time.Time) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateAvailableAt() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *GmailPushEventUpsertBulk) SetLeaseUntil(v time.Time) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateLeaseUntil() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *GmailPushEventUpsertBulk) ClearLeaseUntil() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetLastError sets the "last_error" field.
func (u *GmailPushEventUpsertBulk) SetLastError(v string) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateLastError() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateLastError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GmailPushEventUpsertBulk) SetUpdatedAt(v time.Time) *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GmailPushEventUpsertBulk) UpdateUpdatedAt() *GmailPushEventUpsertBulk {
	return u.Update(func(s *GmailPushEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GmailPushEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GmailPushEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GmailPushEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GmailPushEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
