// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/gmailconnection"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// GmailConnectionDelete is the builder for deleting a GmailConnection entity.
type GmailConnectionDelete struct {
	config
	hooks    []Hook
	mutation *GmailConnectionMutation
}

// Where appends a list predicates to the GmailConnectionDelete builder.
func (_d *GmailConnectionDelete) Where(ps ...predicate.GmailConnection) *GmailConnectionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GmailConnectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GmailConnectionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GmailConnectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(gmailconnection.Table, sqlgraph.NewFieldSpec(gmailconnection.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GmailConnectionDeleteOne is the builder for deleting a single GmailConnection entity.
type GmailConnectionDeleteOne struct {
	_d *GmailConnectionDelete
}

// Where appends a list predicates to the GmailConnectionDelete builder.
func (_d *GmailConnectionDeleteOne) Where(ps ...predicate.GmailConnection) *GmailConnectionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GmailConnectionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gmailconnection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GmailConnectionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
