// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/gmailsynclease"
)

// GmailSyncLeaseCreate is the builder for creating a GmailSyncLease entity.
type GmailSyncLeaseCreate struct {
	config
	mutation *GmailSyncLeaseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOwner sets the "owner" field.
func (_c *GmailSyncLeaseCreate) SetOwner(v string) *GmailSyncLeaseCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *GmailSyncLeaseCreate) SetExpiresAt(v time.Time) *GmailSyncLeaseCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GmailSyncLeaseCreate) SetID(v string) *GmailSyncLeaseCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GmailSyncLeaseMutation object of the builder.
func (_c *GmailSyncLeaseCreate) Mutation() *GmailSyncLeaseMutation {
	return _c.mutation
}

// Save creates the GmailSyncLease in the database.
func (_c *GmailSyncLeaseCreate) Save(ctx context.Context) (*GmailSyncLease, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GmailSyncLeaseCreate) SaveX(ctx context.Context) *GmailSyncLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GmailSyncLeaseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GmailSyncLeaseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GmailSyncLeaseCreate) check() error {
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "GmailSyncLease.owner"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "GmailSyncLease.expires_at"`)}
	}
	return nil
}

func (_c *GmailSyncLeaseCreate) sqlSave(ctx context.Context) (*GmailSyncLease, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected GmailSyncLease.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GmailSyncLeaseCreate) createSpec() (*GmailSyncLease, *sqlgraph.CreateSpec) {
	var (
		_node = &GmailSyncLease{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gmailsynclease.Table, sqlgraph.NewFieldSpec(gmailsynclease.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(gmailsynclease.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(gmailsynclease.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GmailSyncLease.Create().
//		SetOwner(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GmailSyncLeaseUpsert) {
//			SetOwner(v+v).
//		}).
//		Exec(ctx)
func (_c *GmailSyncLeaseCreate) OnConflict(opts ...sql.ConflictOption) *GmailSyncLeaseUpsertOne {
	_c.conflict = opts
	return &GmailSyncLeaseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GmailSyncLeaseCreate) OnConflictColumns(columns ...string) *GmailSyncLeaseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GmailSyncLeaseUpsertOne{
		create: _c,
	}
}

type (
	// GmailSyncLeaseUpsertOne is the builder for "upsert"-ing
	//  one GmailSyncLease node.
	GmailSyncLeaseUpsertOne struct {
		create *GmailSyncLeaseCreate
	}

	// GmailSyncLeaseUpsert is the "OnConflict" setter.
	GmailSyncLeaseUpsert struct {
		*sql.UpdateSet
	}
)

// SetOwner sets the "owner" field.
func (u *GmailSyncLeaseUpsert) SetOwner(v string) *GmailSyncLeaseUpsert {
	u.Set(gmailsynclease.FieldOwner, v)
	return u
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsert) UpdateOwner() *GmailSyncLeaseUpsert {
	u.SetExcluded(gmailsynclease.FieldOwner)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *GmailSyncLeaseUpsert) SetExpiresAt(v time.Time) *GmailSyncLeaseUpsert {
	u.Set(gmailsynclease.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsert) UpdateExpiresAt() *GmailSyncLeaseUpsert {
	u.SetExcluded(gmailsynclease.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gmailsynclease.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GmailSyncLeaseUpsertOne) UpdateNewValues() *GmailSyncLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(gmailsynclease.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GmailSyncLeaseUpsertOne) Ignore() *GmailSyncLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GmailSyncLeaseUpsertOne) DoNothing() *GmailSyncLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GmailSyncLeaseCreate.OnConflict
// documentation for more info.
func (u *GmailSyncLeaseUpsertOne) Update(set func(*GmailSyncLeaseUpsert)) *GmailSyncLeaseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GmailSyncLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwner sets the "owner" field.
func (u *GmailSyncLeaseUpsertOne) SetOwner(v string) *GmailSyncLeaseUpsertOne {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.SetOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsertOne) UpdateOwner() *GmailSyncLeaseUpsertOne {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.UpdateOwner()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GmailSyncLeaseUpsertOne) SetExpiresAt(v time.Time) *GmailSyncLeaseUpsertOne {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsertOne) UpdateExpiresAt() *GmailSyncLeaseUpsertOne {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *GmailSyncLeaseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GmailSyncLeaseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GmailSyncLeaseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GmailSyncLeaseUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GmailSyncLeaseUpsertOne.ID is not supported by MySQL driver. Use GmailSyncLeaseUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GmailSyncLeaseUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GmailSyncLeaseCreateBulk is the builder for creating many GmailSyncLease entities in bulk.
type GmailSyncLeaseCreateBulk struct {
	config
	err      error
	builders []*GmailSyncLeaseCreate
	conflict []sql.ConflictOption
}

// Save creates the GmailSyncLease entities in the database.
func (_c *GmailSyncLeaseCreateBulk) Save(ctx context.Context) ([]*GmailSyncLease, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GmailSyncLease, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GmailSyncLeaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GmailSyncLeaseCreateBulk) SaveX(ctx context.Context) []*GmailSyncLease {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GmailSyncLeaseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GmailSyncLeaseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GmailSyncLease.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GmailSyncLeaseUpsert) {
//			SetOwner(v+v).
//		}).
//		Exec(ctx)
func (_c *GmailSyncLeaseCreateBulk) OnConflict(opts ...sql.ConflictOption) *GmailSyncLeaseUpsertBulk {
	_c.conflict = opts
	return &GmailSyncLeaseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GmailSyncLeaseCreateBulk) OnConflictColumns(columns ...string) *GmailSyncLeaseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GmailSyncLeaseUpsertBulk{
		create: _c,
	}
}

// GmailSyncLeaseUpsertBulk is the builder for "upsert"-ing
// a bulk of GmailSyncLease nodes.
type GmailSyncLeaseUpsertBulk struct {
	create *GmailSyncLeaseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gmailsynclease.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GmailSyncLeaseUpsertBulk) UpdateNewValues() *GmailSyncLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(gmailsynclease.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GmailSyncLease.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GmailSyncLeaseUpsertBulk) Ignore() *GmailSyncLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GmailSyncLeaseUpsertBulk) DoNothing() *GmailSyncLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GmailSyncLeaseCreateBulk.OnConflict
// documentation for more info.
func (u *GmailSyncLeaseUpsertBulk) Update(set func(*GmailSyncLeaseUpsert)) *GmailSyncLeaseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GmailSyncLeaseUpsert{UpdateSet: update})
	}))
	return u
}

// SetOwner sets the "owner" field.
func (u *GmailSyncLeaseUpsertBulk) SetOwner(v string) *GmailSyncLeaseUpsertBulk {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.SetOwner(v)
	})
}

// UpdateOwner sets the "owner" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsertBulk) UpdateOwner() *GmailSyncLeaseUpsertBulk {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.UpdateOwner()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GmailSyncLeaseUpsertBulk) SetExpiresAt(v time.Time) *GmailSyncLeaseUpsertBulk {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GmailSyncLeaseUpsertBulk) UpdateExpiresAt() *GmailSyncLeaseUpsertBulk {
	return u.Update(func(s *GmailSyncLeaseUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *GmailSyncLeaseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GmailSyncLeaseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GmailSyncLeaseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GmailSyncLeaseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
