// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/importjob"
)

// ImportJobCreate is the builder for creating a ImportJob entity.
type ImportJobCreate struct {
	config
	mutation *ImportJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProvider sets the "provider" field.
func (_c *ImportJobCreate) SetProvider(v string) *ImportJobCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetOriginalFilename sets the "original_filename" field.
func (_c *ImportJobCreate) SetOriginalFilename(v string) *ImportJobCreate {
	_c.mutation.SetOriginalFilename(v)
	return _c
}

// SetInputFilename sets the "input_filename" field.
func (_c *ImportJobCreate) SetInputFilename(v string) *ImportJobCreate {
	_c.mutation.SetInputFilename(v)
	return _c
}

// SetNillableInputFilename sets the "input_filename" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableInputFilename(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetInputFilename(*v)
	}
	return _c
}

// SetInputFileKey sets the "input_file_key" field.
func (_c *ImportJobCreate) SetInputFileKey(v string) *ImportJobCreate {
	_c.mutation.SetInputFileKey(v)
	return _c
}

// SetNillableInputFileKey sets the "input_file_key" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableInputFileKey(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetInputFileKey(*v)
	}
	return _c
}

// SetDocumentFileKey sets the "document_file_key" field.
func (_c *ImportJobCreate) SetDocumentFileKey(v string) *ImportJobCreate {
	_c.mutation.SetDocumentFileKey(v)
	return _c
}

// SetNillableDocumentFileKey sets the "document_file_key" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableDocumentFileKey(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetDocumentFileKey(*v)
	}
	return _c
}

// SetGeneratedFileKey sets the "generated_file_key" field.
func (_c *ImportJobCreate) SetGeneratedFileKey(v string) *ImportJobCreate {
	_c.mutation.SetGeneratedFileKey(v)
	return _c
}

// SetNillableGeneratedFileKey sets the "generated_file_key" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableGeneratedFileKey(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetGeneratedFileKey(*v)
	}
	return _c
}

// SetDedupedFileKey sets the "deduped_file_key" field.
func (_c *ImportJobCreate) SetDedupedFileKey(v string) *ImportJobCreate {
	_c.mutation.SetDedupedFileKey(v)
	return _c
}

// SetNillableDedupedFileKey sets the "deduped_file_key" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableDedupedFileKey(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetDedupedFileKey(*v)
	}
	return _c
}

// SetDetectionProvider sets the "detection_provider" field.
func (_c *ImportJobCreate) SetDetectionProvider(v string) *ImportJobCreate {
	_c.mutation.SetDetectionProvider(v)
	return _c
}

// SetDetectionReason sets the "detection_reason" field.
func (_c *ImportJobCreate) SetDetectionReason(v string) *ImportJobCreate {
	_c.mutation.SetDetectionReason(v)
	return _c
}

// SetDetectionConfidence sets the "detection_confidence" field.
func (_c *ImportJobCreate) SetDetectionConfidence(v string) *ImportJobCreate {
	_c.mutation.SetDetectionConfidence(v)
	return _c
}

// SetStatementHash sets the "statement_hash" field.
func (_c *ImportJobCreate) SetStatementHash(v string) *ImportJobCreate {
	_c.mutation.SetStatementHash(v)
	return _c
}

// SetDateStart sets the "date_start" field.
func (_c *ImportJobCreate) SetDateStart(v string) *ImportJobCreate {
	_c.mutation.SetDateStart(v)
	return _c
}

// SetNillableDateStart sets the "date_start" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableDateStart(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetDateStart(*v)
	}
	return _c
}

// SetDateEnd sets the "date_end" field.
func (_c *ImportJobCreate) SetDateEnd(v string) *ImportJobCreate {
	_c.mutation.SetDateEnd(v)
	return _c
}

// SetNillableDateEnd sets the "date_end" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableDateEnd(v *string) *ImportJobCreate {
	if v != nil {
		_c.SetDateEnd(*v)
	}
	return _c
}

// SetExpectedEntryCount sets the "expected_entry_count" field.
func (_c *ImportJobCreate) SetExpectedEntryCount(v int) *ImportJobCreate {
	_c.mutation.SetExpectedEntryCount(v)
	return _c
}

// SetNillableExpectedEntryCount sets the "expected_entry_count" field if the given value is not nil.
func (_c *ImportJobCreate) SetNillableExpectedEntryCount(v *int) *ImportJobCreate {
	if v != nil {
		_c.SetExpectedEntryCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImportJobCreate) SetCreatedAt(v time.Time) *ImportJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImportJobCreate) SetUpdatedAt(v time.Time) *ImportJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ImportJobCreate) SetID(v string) *ImportJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ImportJobMutation object of the builder.
func (_c *ImportJobCreate) Mutation() *ImportJobMutation {
	return _c.mutation
}

// Save creates the ImportJob in the database.
func (_c *ImportJobCreate) Save(ctx context.Context) (*ImportJob, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImportJobCreate) SaveX(ctx context.Context) *ImportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImportJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImportJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImportJobCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ImportJob.provider"`)}
	}
	if _, ok := _c.mutation.OriginalFilename(); !ok {
		return &ValidationError{Name: "original_filename", err: errors.New(`ent: missing required field "ImportJob.original_filename"`)}
	}
	if _, ok := _c.mutation.DetectionProvider(); !ok {
		return &ValidationError{Name: "detection_provider", err: errors.New(`ent: missing required field "ImportJob.detection_provider"`)}
	}
	if _, ok := _c.mutation.DetectionReason(); !ok {
		return &ValidationError{Name: "detection_reason", err: errors.New(`ent: missing required field "ImportJob.detection_reason"`)}
	}
	if _, ok := _c.mutation.DetectionConfidence(); !ok {
		return &ValidationError{Name: "detection_confidence", err: errors.New(`ent: missing required field "ImportJob.detection_confidence"`)}
	}
	if _, ok := _c.mutation.StatementHash(); !ok {
		return &ValidationError{Name: "statement_hash", err: errors.New(`ent: missing required field "ImportJob.statement_hash"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImportJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImportJob.updated_at"`)}
	}
	return nil
}

func (_c *ImportJobCreate) sqlSave(ctx context.Context) (*ImportJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ImportJob.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImportJobCreate) createSpec() (*ImportJob, *sqlgraph.CreateSpec) {
	var (
		_node = &ImportJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(importjob.Table, sqlgraph.NewFieldSpec(importjob.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(importjob.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.OriginalFilename(); ok {
		_spec.SetField(importjob.FieldOriginalFilename, field.TypeString, value)
		_node.OriginalFilename = value
	}
	if value, ok := _c.mutation.InputFilename(); ok {
		_spec.SetField(importjob.FieldInputFilename, field.TypeString, value)
		_node.InputFilename = value
	}
	if value, ok := _c.mutation.InputFileKey(); ok {
		_spec.SetField(importjob.FieldInputFileKey, field.TypeString, value)
		_node.InputFileKey = value
	}
	if value, ok := _c.mutation.DocumentFileKey(); ok {
		_spec.SetField(importjob.FieldDocumentFileKey, field.TypeString, value)
		_node.DocumentFileKey = value
	}
	if value, ok := _c.mutation.GeneratedFileKey(); ok {
		_spec.SetField(importjob.FieldGeneratedFileKey, field.TypeString, value)
		_node.GeneratedFileKey = value
	}
	if value, ok := _c.mutation.DedupedFileKey(); ok {
		_spec.SetField(importjob.FieldDedupedFileKey, field.TypeString, value)
		_node.DedupedFileKey = value
	}
	if value, ok := _c.mutation.DetectionProvider(); ok {
		_spec.SetField(importjob.FieldDetectionProvider, field.TypeString, value)
		_node.DetectionProvider = value
	}
	if value, ok := _c.mutation.DetectionReason(); ok {
		_spec.SetField(importjob.FieldDetectionReason, field.TypeString, value)
		_node.DetectionReason = value
	}
	if value, ok := _c.mutation.DetectionConfidence(); ok {
		_spec.SetField(importjob.FieldDetectionConfidence, field.TypeString, value)
		_node.DetectionConfidence = value
	}
	if value, ok := _c.mutation.StatementHash(); ok {
		_spec.SetField(importjob.FieldStatementHash, field.TypeString, value)
		_node.StatementHash = value
	}
	if value, ok := _c.mutation.DateStart(); ok {
		_spec.SetField(importjob.FieldDateStart, field.TypeString, value)
		_node.DateStart = value
	}
	if value, ok := _c.mutation.DateEnd(); ok {
		_spec.SetField(importjob.FieldDateEnd, field.TypeString, value)
		_node.DateEnd = value
	}
	if value, ok := _c.mutation.ExpectedEntryCount(); ok {
		_spec.SetField(importjob.FieldExpectedEntryCount, field.TypeInt, value)
		_node.ExpectedEntryCount = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(importjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(importjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImportJob.Create().
//		SetProvider(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImportJobUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *ImportJobCreate) OnConflict(opts ...sql.ConflictOption) *ImportJobUpsertOne {
	_c.conflict = opts
	return &ImportJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImportJobCreate) OnConflictColumns(columns ...string) *ImportJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImportJobUpsertOne{
		create: _c,
	}
}

type (
	// ImportJobUpsertOne is the builder for "upsert"-ing
	//  one ImportJob node.
	ImportJobUpsertOne struct {
		create *ImportJobCreate
	}

	// ImportJobUpsert is the "OnConflict" setter.
	ImportJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetProvider sets the "provider" field.
func (u *ImportJobUpsert) SetProvider(v string) *ImportJobUpsert {
	u.Set(importjob.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateProvider() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldProvider)
	return u
}

// SetOriginalFilename sets the "original_filename" field.
func (u *ImportJobUpsert) SetOriginalFilename(v string) *ImportJobUpsert {
	u.Set(importjob.FieldOriginalFilename, v)
	return u
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateOriginalFilename() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldOriginalFilename)
	return u
}

// SetInputFilename sets the "input_filename" field.
func (u *ImportJobUpsert) SetInputFilename(v string) *ImportJobUpsert {
	u.Set(importjob.FieldInputFilename, v)
	return u
}

// UpdateInputFilename sets the "input_filename" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateInputFilename() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldInputFilename)
	return u
}

// ClearInputFilename clears the value of the "input_filename" field.
func (u *ImportJobUpsert) ClearInputFilename() *ImportJobUpsert {
	u.SetNull(importjob.FieldInputFilename)
	return u
}

// SetInputFileKey sets the "input_file_key" field.
func (u *ImportJobUpsert) SetInputFileKey(v string) *ImportJobUpsert {
	u.Set(importjob.FieldInputFileKey, v)
	return u
}

// UpdateInputFileKey sets the "input_file_key" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateInputFileKey() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldInputFileKey)
	return u
}

// ClearInputFileKey clears the value of the "input_file_key" field.
func (u *ImportJobUpsert) ClearInputFileKey() *ImportJobUpsert {
	u.SetNull(importjob.FieldInputFileKey)
	return u
}

// SetDocumentFileKey sets the "document_file_key" field.
func (u *ImportJobUpsert) SetDocumentFileKey(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDocumentFileKey, v)
	return u
}

// UpdateDocumentFileKey sets the "document_file_key" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDocumentFileKey() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDocumentFileKey)
	return u
}

// ClearDocumentFileKey clears the value of the "document_file_key" field.
func (u *ImportJobUpsert) ClearDocumentFileKey() *ImportJobUpsert {
	u.SetNull(importjob.FieldDocumentFileKey)
	return u
}

// SetGeneratedFileKey sets the "generated_file_key" field.
func (u *ImportJobUpsert) SetGeneratedFileKey(v string) *ImportJobUpsert {
	u.Set(importjob.FieldGeneratedFileKey, v)
	return u
}

// UpdateGeneratedFileKey sets the "generated_file_key" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateGeneratedFileKey() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldGeneratedFileKey)
	return u
}

// ClearGeneratedFileKey clears the value of the "generated_file_key" field.
func (u *ImportJobUpsert) ClearGeneratedFileKey() *ImportJobUpsert {
	u.SetNull(importjob.FieldGeneratedFileKey)
	return u
}

// SetDedupedFileKey sets the "deduped_file_key" field.
func (u *ImportJobUpsert) SetDedupedFileKey(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDedupedFileKey, v)
	return u
}

// UpdateDedupedFileKey sets the "deduped_file_key" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDedupedFileKey() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDedupedFileKey)
	return u
}

// ClearDedupedFileKey clears the value of the "deduped_file_key" field.
func (u *ImportJobUpsert) ClearDedupedFileKey() *ImportJobUpsert {
	u.SetNull(importjob.FieldDedupedFileKey)
	return u
}

// SetDetectionProvider sets the "detection_provider" field.
func (u *ImportJobUpsert) SetDetectionProvider(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDetectionProvider, v)
	return u
}

// UpdateDetectionProvider sets the "detection_provider" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDetectionProvider() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDetectionProvider)
	return u
}

// SetDetectionReason sets the "detection_reason" field.
func (u *ImportJobUpsert) SetDetectionReason(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDetectionReason, v)
	return u
}

// UpdateDetectionReason sets the "detection_reason" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDetectionReason() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDetectionReason)
	return u
}

// SetDetectionConfidence sets the "detection_confidence" field.
func (u *ImportJobUpsert) SetDetectionConfidence(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDetectionConfidence, v)
	return u
}

// UpdateDetectionConfidence sets the "detection_confidence" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDetectionConfidence() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDetectionConfidence)
	return u
}

// SetStatementHash sets the "statement_hash" field.
func (u *ImportJobUpsert) SetStatementHash(v string) *ImportJobUpsert {
	u.Set(importjob.FieldStatementHash, v)
	return u
}

// UpdateStatementHash sets the "statement_hash" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateStatementHash() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldStatementHash)
	return u
}

// SetDateStart sets the "date_start" field.
func (u *ImportJobUpsert) SetDateStart(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDateStart, v)
	return u
}

// UpdateDateStart sets the "date_start" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDateStart() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDateStart)
	return u
}

// ClearDateStart clears the value of the "date_start" field.
func (u *ImportJobUpsert) ClearDateStart() *ImportJobUpsert {
	u.SetNull(importjob.FieldDateStart)
	return u
}

// SetDateEnd sets the "date_end" field.
func (u *ImportJobUpsert) SetDateEnd(v string) *ImportJobUpsert {
	u.Set(importjob.FieldDateEnd, v)
	return u
}

// UpdateDateEnd sets the "date_end" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateDateEnd() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldDateEnd)
	return u
}

// ClearDateEnd clears the value of the "date_end" field.
func (u *ImportJobUpsert) ClearDateEnd() *ImportJobUpsert {
	u.SetNull(importjob.FieldDateEnd)
	return u
}

// SetExpectedEntryCount sets the "expected_entry_count" field.
func (u *ImportJobUpsert) SetExpectedEntryCount(v int) *ImportJobUpsert {
	u.Set(importjob.FieldExpectedEntryCount, v)
	return u
}

// UpdateExpectedEntryCount sets the "expected_entry_count" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateExpectedEntryCount() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldExpectedEntryCount)
	return u
}

// AddExpectedEntryCount adds v to the "expected_entry_count" field.
func (u *ImportJobUpsert) AddExpectedEntryCount(v int) *ImportJobUpsert {
	u.Add(importjob.FieldExpectedEntryCount, v)
	return u
}

// ClearExpectedEntryCount clears the value of the "expected_entry_count" field.
func (u *ImportJobUpsert) ClearExpectedEntryCount() *ImportJobUpsert {
	u.SetNull(importjob.FieldExpectedEntryCount)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImportJobUpsert) SetUpdatedAt(v time.Time) *ImportJobUpsert {
	u.Set(importjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImportJobUpsert) UpdateUpdatedAt() *ImportJobUpsert {
	u.SetExcluded(importjob.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(importjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImportJobUpsertOne) UpdateNewValues() *ImportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(importjob.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(importjob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImportJobUpsertOne) Ignore() *ImportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImportJobUpsertOne) DoNothing() *ImportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImportJobCreate.OnConflict
// documentation for more info.
func (u *ImportJobUpsertOne) Update(set func(*ImportJobUpsert)) *ImportJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImportJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ImportJobUpsertOne) SetProvider(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateProvider() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateProvider()
	})
}

// SetOriginalFilename sets the "original_filename" field.
func (u *ImportJobUpsertOne) SetOriginalFilename(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetOriginalFilename(v)
	})
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateOriginalFilename() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateOriginalFilename()
	})
}

// SetInputFilename sets the "input_filename" field.
func (u *ImportJobUpsertOne) SetInputFilename(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetInputFilename(v)
	})
}

// UpdateInputFilename sets the "input_filename" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateInputFilename() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateInputFilename()
	})
}

// ClearInputFilename clears the value of the "input_filename" field.
func (u *ImportJobUpsertOne) ClearInputFilename() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearInputFilename()
	})
}

// SetInputFileKey sets the "input_file_key" field.
func (u *ImportJobUpsertOne) SetInputFileKey(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetInputFileKey(v)
	})
}

// UpdateInputFileKey sets the "input_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateInputFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateInputFileKey()
	})
}

// ClearInputFileKey clears the value of the "input_file_key" field.
func (u *ImportJobUpsertOne) ClearInputFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearInputFileKey()
	})
}

// SetDocumentFileKey sets the "document_file_key" field.
func (u *ImportJobUpsertOne) SetDocumentFileKey(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDocumentFileKey(v)
	})
}

// UpdateDocumentFileKey sets the "document_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDocumentFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDocumentFileKey()
	})
}

// ClearDocumentFileKey clears the value of the "document_file_key" field.
func (u *ImportJobUpsertOne) ClearDocumentFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDocumentFileKey()
	})
}

// SetGeneratedFileKey sets the "generated_file_key" field.
func (u *ImportJobUpsertOne) SetGeneratedFileKey(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetGeneratedFileKey(v)
	})
}

// UpdateGeneratedFileKey sets the "generated_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateGeneratedFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateGeneratedFileKey()
	})
}

// ClearGeneratedFileKey clears the value of the "generated_file_key" field.
func (u *ImportJobUpsertOne) ClearGeneratedFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearGeneratedFileKey()
	})
}

// SetDedupedFileKey sets the "deduped_file_key" field.
func (u *ImportJobUpsertOne) SetDedupedFileKey(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDedupedFileKey(v)
	})
}

// UpdateDedupedFileKey sets the "deduped_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDedupedFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDedupedFileKey()
	})
}

// ClearDedupedFileKey clears the value of the "deduped_file_key" field.
func (u *ImportJobUpsertOne) ClearDedupedFileKey() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDedupedFileKey()
	})
}

// SetDetectionProvider sets the "detection_provider" field.
func (u *ImportJobUpsertOne) SetDetectionProvider(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionProvider(v)
	})
}

// UpdateDetectionProvider sets the "detection_provider" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDetectionProvider() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionProvider()
	})
}

// SetDetectionReason sets the "detection_reason" field.
func (u *ImportJobUpsertOne) SetDetectionReason(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionReason(v)
	})
}

// UpdateDetectionReason sets the "detection_reason" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDetectionReason() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionReason()
	})
}

// SetDetectionConfidence sets the "detection_confidence" field.
func (u *ImportJobUpsertOne) SetDetectionConfidence(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionConfidence(v)
	})
}

// UpdateDetectionConfidence sets the "detection_confidence" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDetectionConfidence() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionConfidence()
	})
}

// SetStatementHash sets the "statement_hash" field.
func (u *ImportJobUpsertOne) SetStatementHash(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetStatementHash(v)
	})
}

// UpdateStatementHash sets the "statement_hash" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateStatementHash() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateStatementHash()
	})
}

// SetDateStart sets the "date_start" field.
func (u *ImportJobUpsertOne) SetDateStart(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDateStart(v)
	})
}

// UpdateDateStart sets the "date_start" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDateStart() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDateStart()
	})
}

// ClearDateStart clears the value of the "date_start" field.
func (u *ImportJobUpsertOne) ClearDateStart() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDateStart()
	})
}

// SetDateEnd sets the "date_end" field.
func (u *ImportJobUpsertOne) SetDateEnd(v string) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDateEnd(v)
	})
}

// UpdateDateEnd sets the "date_end" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateDateEnd() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDateEnd()
	})
}

// ClearDateEnd clears the value of the "date_end" field.
func (u *ImportJobUpsertOne) ClearDateEnd() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDateEnd()
	})
}

// SetExpectedEntryCount sets the "expected_entry_count" field.
func (u *ImportJobUpsertOne) SetExpectedEntryCount(v int) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetExpectedEntryCount(v)
	})
}

// AddExpectedEntryCount adds v to the "expected_entry_count" field.
func (u *ImportJobUpsertOne) AddExpectedEntryCount(v int) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.AddExpectedEntryCount(v)
	})
}

// UpdateExpectedEntryCount sets the "expected_entry_count" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateExpectedEntryCount() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateExpectedEntryCount()
	})
}

// ClearExpectedEntryCount clears the value of the "expected_entry_count" field.
func (u *ImportJobUpsertOne) ClearExpectedEntryCount() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearExpectedEntryCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImportJobUpsertOne) SetUpdatedAt(v time.Time) *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImportJobUpsertOne) UpdateUpdatedAt() *ImportJobUpsertOne {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ImportJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImportJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImportJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImportJobUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ImportJobUpsertOne.ID is not supported by MySQL driver. Use ImportJobUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImportJobUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImportJobCreateBulk is the builder for creating many ImportJob entities in bulk.
type ImportJobCreateBulk struct {
	config
	err      error
	builders []*ImportJobCreate
	conflict []sql.ConflictOption
}

// Save creates the ImportJob entities in the database.
func (_c *ImportJobCreateBulk) Save(ctx context.Context) ([]*ImportJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImportJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImportJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImportJobCreateBulk) SaveX(ctx context.Context) []*ImportJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImportJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImportJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImportJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImportJobUpsert) {
//			SetProvider(v+v).
//		}).
//		Exec(ctx)
func (_c *ImportJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImportJobUpsertBulk {
	_c.conflict = opts
	return &ImportJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImportJobCreateBulk) OnConflictColumns(columns ...string) *ImportJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImportJobUpsertBulk{
		create: _c,
	}
}

// ImportJobUpsertBulk is the builder for "upsert"-ing
// a bulk of ImportJob nodes.
type ImportJobUpsertBulk struct {
	create *ImportJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(importjob.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImportJobUpsertBulk) UpdateNewValues() *ImportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(importjob.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(importjob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImportJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImportJobUpsertBulk) Ignore() *ImportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImportJobUpsertBulk) DoNothing() *ImportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImportJobCreateBulk.OnConflict
// documentation for more info.
func (u *ImportJobUpsertBulk) Update(set func(*ImportJobUpsert)) *ImportJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImportJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetProvider sets the "provider" field.
func (u *ImportJobUpsertBulk) SetProvider(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateProvider() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateProvider()
	})
}

// SetOriginalFilename sets the "original_filename" field.
func (u *ImportJobUpsertBulk) SetOriginalFilename(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetOriginalFilename(v)
	})
}

// UpdateOriginalFilename sets the "original_filename" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateOriginalFilename() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateOriginalFilename()
	})
}

// SetInputFilename sets the "input_filename" field.
func (u *ImportJobUpsertBulk) SetInputFilename(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetInputFilename(v)
	})
}

// UpdateInputFilename sets the "input_filename" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateInputFilename() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateInputFilename()
	})
}

// ClearInputFilename clears the value of the "input_filename" field.
func (u *ImportJobUpsertBulk) ClearInputFilename() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearInputFilename()
	})
}

// SetInputFileKey sets the "input_file_key" field.
func (u *ImportJobUpsertBulk) SetInputFileKey(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetInputFileKey(v)
	})
}

// UpdateInputFileKey sets the "input_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateInputFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateInputFileKey()
	})
}

// ClearInputFileKey clears the value of the "input_file_key" field.
func (u *ImportJobUpsertBulk) ClearInputFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearInputFileKey()
	})
}

// SetDocumentFileKey sets the "document_file_key" field.
func (u *ImportJobUpsertBulk) SetDocumentFileKey(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDocumentFileKey(v)
	})
}

// UpdateDocumentFileKey sets the "document_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDocumentFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDocumentFileKey()
	})
}

// ClearDocumentFileKey clears the value of the "document_file_key" field.
func (u *ImportJobUpsertBulk) ClearDocumentFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDocumentFileKey()
	})
}

// SetGeneratedFileKey sets the "generated_file_key" field.
func (u *ImportJobUpsertBulk) SetGeneratedFileKey(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetGeneratedFileKey(v)
	})
}

// UpdateGeneratedFileKey sets the "generated_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateGeneratedFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateGeneratedFileKey()
	})
}

// ClearGeneratedFileKey clears the value of the "generated_file_key" field.
func (u *ImportJobUpsertBulk) ClearGeneratedFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearGeneratedFileKey()
	})
}

// SetDedupedFileKey sets the "deduped_file_key" field.
func (u *ImportJobUpsertBulk) SetDedupedFileKey(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDedupedFileKey(v)
	})
}

// UpdateDedupedFileKey sets the "deduped_file_key" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDedupedFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDedupedFileKey()
	})
}

// ClearDedupedFileKey clears the value of the "deduped_file_key" field.
func (u *ImportJobUpsertBulk) ClearDedupedFileKey() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDedupedFileKey()
	})
}

// SetDetectionProvider sets the "detection_provider" field.
func (u *ImportJobUpsertBulk) SetDetectionProvider(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionProvider(v)
	})
}

// UpdateDetectionProvider sets the "detection_provider" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDetectionProvider() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionProvider()
	})
}

// SetDetectionReason sets the "detection_reason" field.
func (u *ImportJobUpsertBulk) SetDetectionReason(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionReason(v)
	})
}

// UpdateDetectionReason sets the "detection_reason" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDetectionReason() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionReason()
	})
}

// SetDetectionConfidence sets the "detection_confidence" field.
func (u *ImportJobUpsertBulk) SetDetectionConfidence(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDetectionConfidence(v)
	})
}

// UpdateDetectionConfidence sets the "detection_confidence" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDetectionConfidence() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDetectionConfidence()
	})
}

// SetStatementHash sets the "statement_hash" field.
func (u *ImportJobUpsertBulk) SetStatementHash(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetStatementHash(v)
	})
}

// UpdateStatementHash sets the "statement_hash" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateStatementHash() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateStatementHash()
	})
}

// SetDateStart sets the "date_start" field.
func (u *ImportJobUpsertBulk) SetDateStart(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDateStart(v)
	})
}

// UpdateDateStart sets the "date_start" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDateStart() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDateStart()
	})
}

// ClearDateStart clears the value of the "date_start" field.
func (u *ImportJobUpsertBulk) ClearDateStart() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDateStart()
	})
}

// SetDateEnd sets the "date_end" field.
func (u *ImportJobUpsertBulk) SetDateEnd(v string) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetDateEnd(v)
	})
}

// UpdateDateEnd sets the "date_end" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateDateEnd() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateDateEnd()
	})
}

// ClearDateEnd clears the value of the "date_end" field.
func (u *ImportJobUpsertBulk) ClearDateEnd() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearDateEnd()
	})
}

// SetExpectedEntryCount sets the "expected_entry_count" field.
func (u *ImportJobUpsertBulk) SetExpectedEntryCount(v int) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetExpectedEntryCount(v)
	})
}

// AddExpectedEntryCount adds v to the "expected_entry_count" field.
func (u *ImportJobUpsertBulk) AddExpectedEntryCount(v int) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.AddExpectedEntryCount(v)
	})
}

// UpdateExpectedEntryCount sets the "expected_entry_count" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateExpectedEntryCount() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateExpectedEntryCount()
	})
}

// ClearExpectedEntryCount clears the value of the "expected_entry_count" field.
func (u *ImportJobUpsertBulk) ClearExpectedEntryCount() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.ClearExpectedEntryCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImportJobUpsertBulk) SetUpdatedAt(v time.Time) *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImportJobUpsertBulk) UpdateUpdatedAt() *ImportJobUpsertBulk {
	return u.Update(func(s *ImportJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ImportJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImportJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImportJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImportJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
