// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/importjob"
)

// ImportJob is the model entity for the ImportJob schema.
type ImportJob struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// OriginalFilename holds the value of the "original_filename" field.
	OriginalFilename string `json:"original_filename,omitempty"`
	// InputFilename holds the value of the "input_filename" field.
	InputFilename string `json:"input_filename,omitempty"`
	// InputFileKey holds the value of the "input_file_key" field.
	InputFileKey string `json:"input_file_key,omitempty"`
	// DocumentFileKey holds the value of the "document_file_key" field.
	DocumentFileKey string `json:"document_file_key,omitempty"`
	// GeneratedFileKey holds the value of the "generated_file_key" field.
	GeneratedFileKey string `json:"generated_file_key,omitempty"`
	// DedupedFileKey holds the value of the "deduped_file_key" field.
	DedupedFileKey string `json:"deduped_file_key,omitempty"`
	// DetectionProvider holds the value of the "detection_provider" field.
	DetectionProvider string `json:"detection_provider,omitempty"`
	// DetectionReason holds the value of the "detection_reason" field.
	DetectionReason string `json:"detection_reason,omitempty"`
	// DetectionConfidence holds the value of the "detection_confidence" field.
	DetectionConfidence string `json:"detection_confidence,omitempty"`
	// StatementHash holds the value of the "statement_hash" field.
	StatementHash string `json:"statement_hash,omitempty"`
	// DateStart holds the value of the "date_start" field.
	DateStart string `json:"date_start,omitempty"`
	// DateEnd holds the value of the "date_end" field.
	DateEnd string `json:"date_end,omitempty"`
	// ExpectedEntryCount holds the value of the "expected_entry_count" field.
	ExpectedEntryCount *int `json:"expected_entry_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImportJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case importjob.FieldExpectedEntryCount:
			values[i] = new(sql.NullInt64)
		case importjob.FieldID, importjob.FieldProvider, importjob.FieldOriginalFilename, importjob.FieldInputFilename, importjob.FieldInputFileKey, importjob.FieldDocumentFileKey, importjob.FieldGeneratedFileKey, importjob.FieldDedupedFileKey, importjob.FieldDetectionProvider, importjob.FieldDetectionReason, importjob.FieldDetectionConfidence, importjob.FieldStatementHash, importjob.FieldDateStart, importjob.FieldDateEnd:
			values[i] = new(sql.NullString)
		case importjob.FieldCreatedAt, importjob.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImportJob fields.
func (_m *ImportJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case importjob.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case importjob.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case importjob.FieldOriginalFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_filename", values[i])
			} else if value.Valid {
				_m.OriginalFilename = value.String
			}
		case importjob.FieldInputFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_filename", values[i])
			} else if value.Valid {
				_m.InputFilename = value.String
			}
		case importjob.FieldInputFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_file_key", values[i])
			} else if value.Valid {
				_m.InputFileKey = value.String
			}
		case importjob.FieldDocumentFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_file_key", values[i])
			} else if value.Valid {
				_m.DocumentFileKey = value.String
			}
		case importjob.FieldGeneratedFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generated_file_key", values[i])
			} else if value.Valid {
				_m.GeneratedFileKey = value.String
			}
		case importjob.FieldDedupedFileKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deduped_file_key", values[i])
			} else if value.Valid {
				_m.DedupedFileKey = value.String
			}
		case importjob.FieldDetectionProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detection_provider", values[i])
			} else if value.Valid {
				_m.DetectionProvider = value.String
			}
		case importjob.FieldDetectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detection_reason", values[i])
			} else if value.Valid {
				_m.DetectionReason = value.String
			}
		case importjob.FieldDetectionConfidence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field detection_confidence", values[i])
			} else if value.Valid {
				_m.DetectionConfidence = value.String
			}
		case importjob.FieldStatementHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field statement_hash", values[i])
			} else if value.Valid {
				_m.StatementHash = value.String
			}
		case importjob.FieldDateStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date_start", values[i])
			} else if value.Valid {
				_m.DateStart = value.String
			}
		case importjob.FieldDateEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date_end", values[i])
			} else if value.Valid {
				_m.DateEnd = value.String
			}
		case importjob.FieldExpectedEntryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expected_entry_count", values[i])
			} else if value.Valid {
				_m.ExpectedEntryCount = new(int)
				*_m.ExpectedEntryCount = int(value.Int64)
			}
		case importjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case importjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImportJob.
// This includes values selected through modifiers, order, etc.
func (_m *ImportJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImportJob.
// Note that you need to call ImportJob.Unwrap() before calling this method if this ImportJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImportJob) Update() *ImportJobUpdateOne {
	return NewImportJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImportJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImportJob) Unwrap() *ImportJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImportJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImportJob) String() string {
	var builder strings.Builder
	builder.WriteString("ImportJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("original_filename=")
	builder.WriteString(_m.OriginalFilename)
	builder.WriteString(", ")
	builder.WriteString("input_filename=")
	builder.WriteString(_m.InputFilename)
	builder.WriteString(", ")
	builder.WriteString("input_file_key=")
	builder.WriteString(_m.InputFileKey)
	builder.WriteString(", ")
	builder.WriteString("document_file_key=")
	builder.WriteString(_m.DocumentFileKey)
	builder.WriteString(", ")
	builder.WriteString("generated_file_key=")
	builder.WriteString(_m.GeneratedFileKey)
	builder.WriteString(", ")
	builder.WriteString("deduped_file_key=")
	builder.WriteString(_m.DedupedFileKey)
	builder.WriteString(", ")
	builder.WriteString("detection_provider=")
	builder.WriteString(_m.DetectionProvider)
	builder.WriteString(", ")
	builder.WriteString("detection_reason=")
	builder.WriteString(_m.DetectionReason)
	builder.WriteString(", ")
	builder.WriteString("detection_confidence=")
	builder.WriteString(_m.DetectionConfidence)
	builder.WriteString(", ")
	builder.WriteString("statement_hash=")
	builder.WriteString(_m.StatementHash)
	builder.WriteString(", ")
	builder.WriteString("date_start=")
	builder.WriteString(_m.DateStart)
	builder.WriteString(", ")
	builder.WriteString("date_end=")
	builder.WriteString(_m.DateEnd)
	builder.WriteString(", ")
	if v := _m.ExpectedEntryCount; v != nil {
		builder.WriteString("expected_entry_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImportJobs is a parsable slice of ImportJob.
type ImportJobs []*ImportJob
