// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/passkeysession"
	"github.com/go-webauthn/webauthn/webauthn"
)

// PasskeySessionCreate is the builder for creating a PasskeySession entity.
type PasskeySessionCreate struct {
	config
	mutation *PasskeySessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetData sets the "data" field.
func (_c *PasskeySessionCreate) SetData(v webauthn.SessionData) *PasskeySessionCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PasskeySessionCreate) SetCreatedAt(v time.Time) *PasskeySessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PasskeySessionCreate) SetExpiresAt(v time.Time) *PasskeySessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PasskeySessionCreate) SetID(v string) *PasskeySessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PasskeySessionMutation object of the builder.
func (_c *PasskeySessionCreate) Mutation() *PasskeySessionMutation {
	return _c.mutation
}

// Save creates the PasskeySession in the database.
func (_c *PasskeySessionCreate) Save(ctx context.Context) (*PasskeySession, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasskeySessionCreate) SaveX(ctx context.Context) *PasskeySession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeySessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeySessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasskeySessionCreate) check() error {
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "PasskeySession.data"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasskeySession.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "PasskeySession.expires_at"`)}
	}
	return nil
}

func (_c *PasskeySessionCreate) sqlSave(ctx context.Context) (*PasskeySession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PasskeySession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasskeySessionCreate) createSpec() (*PasskeySession, *sqlgraph.CreateSpec) {
	var (
		_node = &PasskeySession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passkeysession.Table, sqlgraph.NewFieldSpec(passkeysession.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(passkeysession.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passkeysession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(passkeysession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeySession.Create().
//		SetData(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeySessionUpsert) {
//			SetData(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeySessionCreate) OnConflict(opts ...sql.ConflictOption) *PasskeySessionUpsertOne {
	_c.conflict = opts
	return &PasskeySessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeySessionCreate) OnConflictColumns(columns ...string) *PasskeySessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeySessionUpsertOne{
		create: _c,
	}
}

type (
	// PasskeySessionUpsertOne is the builder for "upsert"-ing
	//  one PasskeySession node.
	PasskeySessionUpsertOne struct {
		create *PasskeySessionCreate
	}

	// PasskeySessionUpsert is the "OnConflict" setter.
	PasskeySessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetData sets the "data" field.
func (u *PasskeySessionUpsert) SetData(v webauthn.SessionData) *PasskeySessionUpsert {
	u.Set(passkeysession.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PasskeySessionUpsert) UpdateData() *PasskeySessionUpsert {
	u.SetExcluded(passkeysession.FieldData)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *PasskeySessionUpsert) SetExpiresAt(v time.Time) *PasskeySessionUpsert {
	u.Set(passkeysession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PasskeySessionUpsert) UpdateExpiresAt() *PasskeySessionUpsert {
	u.SetExcluded(passkeysession.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkeysession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeySessionUpsertOne) UpdateNewValues() *PasskeySessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(passkeysession.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(passkeysession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasskeySessionUpsertOne) Ignore() *PasskeySessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeySessionUpsertOne) DoNothing() *PasskeySessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeySessionCreate.OnConflict
// documentation for more info.
func (u *PasskeySessionUpsertOne) Update(set func(*PasskeySessionUpsert)) *PasskeySessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeySessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetData sets the "data" field.
func (u *PasskeySessionUpsertOne) SetData(v webauthn.SessionData) *PasskeySessionUpsertOne {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PasskeySessionUpsertOne) UpdateData() *PasskeySessionUpsertOne {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.UpdateData()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PasskeySessionUpsertOne) SetExpiresAt(v time.Time) *PasskeySessionUpsertOne {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PasskeySessionUpsertOne) UpdateExpiresAt() *PasskeySessionUpsertOne {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *PasskeySessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeySessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeySessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasskeySessionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PasskeySessionUpsertOne.ID is not supported by MySQL driver. Use PasskeySessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasskeySessionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasskeySessionCreateBulk is the builder for creating many PasskeySession entities in bulk.
type PasskeySessionCreateBulk struct {
	config
	err      error
	builders []*PasskeySessionCreate
	conflict []sql.ConflictOption
}

// Save creates the PasskeySession entities in the database.
func (_c *PasskeySessionCreateBulk) Save(ctx context.Context) ([]*PasskeySession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasskeySession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasskeySessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasskeySessionCreateBulk) SaveX(ctx context.Context) []*PasskeySession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeySessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeySessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeySession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeySessionUpsert) {
//			SetData(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeySessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasskeySessionUpsertBulk {
	_c.conflict = opts
	return &PasskeySessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeySessionCreateBulk) OnConflictColumns(columns ...string) *PasskeySessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeySessionUpsertBulk{
		create: _c,
	}
}

// PasskeySessionUpsertBulk is the builder for "upsert"-ing
// a bulk of PasskeySession nodes.
type PasskeySessionUpsertBulk struct {
	create *PasskeySessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkeysession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeySessionUpsertBulk) UpdateNewValues() *PasskeySessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(passkeysession.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(passkeysession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeySession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasskeySessionUpsertBulk) Ignore() *PasskeySessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeySessionUpsertBulk) DoNothing() *PasskeySessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeySessionCreateBulk.OnConflict
// documentation for more info.
func (u *PasskeySessionUpsertBulk) Update(set func(*PasskeySessionUpsert)) *PasskeySessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeySessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetData sets the "data" field.
func (u *PasskeySessionUpsertBulk) SetData(v webauthn.SessionData) *PasskeySessionUpsertBulk {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *PasskeySessionUpsertBulk) UpdateData() *PasskeySessionUpsertBulk {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.UpdateData()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *PasskeySessionUpsertBulk) SetExpiresAt(v time.Time) *PasskeySessionUpsertBulk {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *PasskeySessionUpsertBulk) UpdateExpiresAt() *PasskeySessionUpsertBulk {
	return u.Update(func(s *PasskeySessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *PasskeySessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasskeySessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeySessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeySessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
