// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/passkeycredential"
)

// PasskeyCredentialCreate is the builder for creating a PasskeyCredential entity.
type PasskeyCredentialCreate struct {
	config
	mutation *PasskeyCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPublicKey sets the "public_key" field.
func (_c *PasskeyCredentialCreate) SetPublicKey(v []byte) *PasskeyCredentialCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetSignCount sets the "sign_count" field.
func (_c *PasskeyCredentialCreate) SetSignCount(v uint64) *PasskeyCredentialCreate {
	_c.mutation.SetSignCount(v)
	return _c
}

// SetBackupEligible sets the "backup_eligible" field.
func (_c *PasskeyCredentialCreate) SetBackupEligible(v bool) *PasskeyCredentialCreate {
	_c.mutation.SetBackupEligible(v)
	return _c
}

// SetNillableBackupEligible sets the "backup_eligible" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableBackupEligible(v *bool) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetBackupEligible(*v)
	}
	return _c
}

// SetBackupState sets the "backup_state" field.
func (_c *PasskeyCredentialCreate) SetBackupState(v bool) *PasskeyCredentialCreate {
	_c.mutation.SetBackupState(v)
	return _c
}

// SetNillableBackupState sets the "backup_state" field if the given value is not nil.
func (_c *PasskeyCredentialCreate) SetNillableBackupState(v *bool) *PasskeyCredentialCreate {
	if v != nil {
		_c.SetBackupState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PasskeyCredentialCreate) SetCreatedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PasskeyCredentialCreate) SetUpdatedAt(v time.Time) *PasskeyCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PasskeyCredentialCreate) SetID(v string) *PasskeyCredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PasskeyCredentialMutation object of the builder.
func (_c *PasskeyCredentialCreate) Mutation() *PasskeyCredentialMutation {
	return _c.mutation
}

// Save creates the PasskeyCredential in the database.
func (_c *PasskeyCredentialCreate) Save(ctx context.Context) (*PasskeyCredential, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PasskeyCredentialCreate) SaveX(ctx context.Context) *PasskeyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PasskeyCredentialCreate) check() error {
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "PasskeyCredential.public_key"`)}
	}
	if _, ok := _c.mutation.SignCount(); !ok {
		return &ValidationError{Name: "sign_count", err: errors.New(`ent: missing required field "PasskeyCredential.sign_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PasskeyCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PasskeyCredential.updated_at"`)}
	}
	return nil
}

func (_c *PasskeyCredentialCreate) sqlSave(ctx context.Context) (*PasskeyCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PasskeyCredential.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PasskeyCredentialCreate) createSpec() (*PasskeyCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &PasskeyCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(passkeycredential.Table, sqlgraph.NewFieldSpec(passkeycredential.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(passkeycredential.FieldPublicKey, field.TypeBytes, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.SignCount(); ok {
		_spec.SetField(passkeycredential.FieldSignCount, field.TypeUint64, value)
		_node.SignCount = value
	}
	if value, ok := _c.mutation.BackupEligible(); ok {
		_spec.SetField(passkeycredential.FieldBackupEligible, field.TypeBool, value)
		_node.BackupEligible = &value
	}
	if value, ok := _c.mutation.BackupState(); ok {
		_spec.SetField(passkeycredential.FieldBackupState, field.TypeBool, value)
		_node.BackupState = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(passkeycredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeycredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeyCredential.Create().
//		SetPublicKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyCredentialUpsert) {
//			SetPublicKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCredentialCreate) OnConflict(opts ...sql.ConflictOption) *PasskeyCredentialUpsertOne {
	_c.conflict = opts
	return &PasskeyCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCredentialCreate) OnConflictColumns(columns ...string) *PasskeyCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyCredentialUpsertOne{
		create: _c,
	}
}

type (
	// PasskeyCredentialUpsertOne is the builder for "upsert"-ing
	//  one PasskeyCredential node.
	PasskeyCredentialUpsertOne struct {
		create *PasskeyCredentialCreate
	}

	// PasskeyCredentialUpsert is the "OnConflict" setter.
	PasskeyCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsert) SetPublicKey(v []byte) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldPublicKey, v)
	return u
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdatePublicKey() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldPublicKey)
	return u
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsert) SetSignCount(v uint64) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldSignCount, v)
	return u
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateSignCount() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldSignCount)
	return u
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsert) AddSignCount(v uint64) *PasskeyCredentialUpsert {
	u.Add(passkeycredential.FieldSignCount, v)
	return u
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsert) SetBackupEligible(v bool) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldBackupEligible, v)
	return u
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateBackupEligible() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldBackupEligible)
	return u
}

// ClearBackupEligible clears the value of the "backup_eligible" field.
func (u *PasskeyCredentialUpsert) ClearBackupEligible() *PasskeyCredentialUpsert {
	u.SetNull(passkeycredential.FieldBackupEligible)
	return u
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsert) SetBackupState(v bool) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldBackupState, v)
	return u
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateBackupState() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldBackupState)
	return u
}

// ClearBackupState clears the value of the "backup_state" field.
func (u *PasskeyCredentialUpsert) ClearBackupState() *PasskeyCredentialUpsert {
	u.SetNull(passkeycredential.FieldBackupState)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsert) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsert {
	u.Set(passkeycredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsert) UpdateUpdatedAt() *PasskeyCredentialUpsert {
	u.SetExcluded(passkeycredential.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkeycredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertOne) UpdateNewValues() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(passkeycredential.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(passkeycredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PasskeyCredentialUpsertOne) Ignore() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyCredentialUpsertOne) DoNothing() *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCredentialCreate.OnConflict
// documentation for more info.
func (u *PasskeyCredentialUpsertOne) Update(set func(*PasskeyCredentialUpsert)) *PasskeyCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsertOne) SetPublicKey(v []byte) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdatePublicKey() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsertOne) SetSignCount(v uint64) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsertOne) AddSignCount(v uint64) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateSignCount() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateSignCount()
	})
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsertOne) SetBackupEligible(v bool) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupEligible(v)
	})
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateBackupEligible() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupEligible()
	})
}

// ClearBackupEligible clears the value of the "backup_eligible" field.
func (u *PasskeyCredentialUpsertOne) ClearBackupEligible() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearBackupEligible()
	})
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsertOne) SetBackupState(v bool) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupState(v)
	})
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateBackupState() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupState()
	})
}

// ClearBackupState clears the value of the "backup_state" field.
func (u *PasskeyCredentialUpsertOne) ClearBackupState() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearBackupState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsertOne) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertOne) UpdateUpdatedAt() *PasskeyCredentialUpsertOne {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PasskeyCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PasskeyCredentialUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PasskeyCredentialUpsertOne.ID is not supported by MySQL driver. Use PasskeyCredentialUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PasskeyCredentialUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PasskeyCredentialCreateBulk is the builder for creating many PasskeyCredential entities in bulk.
type PasskeyCredentialCreateBulk struct {
	config
	err      error
	builders []*PasskeyCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the PasskeyCredential entities in the database.
func (_c *PasskeyCredentialCreateBulk) Save(ctx context.Context) ([]*PasskeyCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PasskeyCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PasskeyCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PasskeyCredentialCreateBulk) SaveX(ctx context.Context) []*PasskeyCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PasskeyCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PasskeyCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PasskeyCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PasskeyCredentialUpsert) {
//			SetPublicKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PasskeyCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *PasskeyCredentialUpsertBulk {
	_c.conflict = opts
	return &PasskeyCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PasskeyCredentialCreateBulk) OnConflictColumns(columns ...string) *PasskeyCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PasskeyCredentialUpsertBulk{
		create: _c,
	}
}

// PasskeyCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of PasskeyCredential nodes.
type PasskeyCredentialUpsertBulk struct {
	create *PasskeyCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(passkeycredential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertBulk) UpdateNewValues() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(passkeycredential.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(passkeycredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PasskeyCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PasskeyCredentialUpsertBulk) Ignore() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PasskeyCredentialUpsertBulk) DoNothing() *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PasskeyCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *PasskeyCredentialUpsertBulk) Update(set func(*PasskeyCredentialUpsert)) *PasskeyCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PasskeyCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicKey sets the "public_key" field.
func (u *PasskeyCredentialUpsertBulk) SetPublicKey(v []byte) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdatePublicKey() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSignCount sets the "sign_count" field.
func (u *PasskeyCredentialUpsertBulk) SetSignCount(v uint64) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetSignCount(v)
	})
}

// AddSignCount adds v to the "sign_count" field.
func (u *PasskeyCredentialUpsertBulk) AddSignCount(v uint64) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.AddSignCount(v)
	})
}

// UpdateSignCount sets the "sign_count" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateSignCount() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateSignCount()
	})
}

// SetBackupEligible sets the "backup_eligible" field.
func (u *PasskeyCredentialUpsertBulk) SetBackupEligible(v bool) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupEligible(v)
	})
}

// UpdateBackupEligible sets the "backup_eligible" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateBackupEligible() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupEligible()
	})
}

// ClearBackupEligible clears the value of the "backup_eligible" field.
func (u *PasskeyCredentialUpsertBulk) ClearBackupEligible() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearBackupEligible()
	})
}

// SetBackupState sets the "backup_state" field.
func (u *PasskeyCredentialUpsertBulk) SetBackupState(v bool) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetBackupState(v)
	})
}

// UpdateBackupState sets the "backup_state" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateBackupState() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateBackupState()
	})
}

// ClearBackupState clears the value of the "backup_state" field.
func (u *PasskeyCredentialUpsertBulk) ClearBackupState() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.ClearBackupState()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PasskeyCredentialUpsertBulk) SetUpdatedAt(v time.Time) *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PasskeyCredentialUpsertBulk) UpdateUpdatedAt() *PasskeyCredentialUpsertBulk {
	return u.Update(func(s *PasskeyCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PasskeyCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PasskeyCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PasskeyCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PasskeyCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
