// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/quickunlockdevice"
)

// QuickUnlockDeviceDelete is the builder for deleting a QuickUnlockDevice entity.
type QuickUnlockDeviceDelete struct {
	config
	hooks    []Hook
	mutation *QuickUnlockDeviceMutation
}

// Where appends a list predicates to the QuickUnlockDeviceDelete builder.
func (_d *QuickUnlockDeviceDelete) Where(ps ...predicate.QuickUnlockDevice) *QuickUnlockDeviceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuickUnlockDeviceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuickUnlockDeviceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuickUnlockDeviceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quickunlockdevice.Table, sqlgraph.NewFieldSpec(quickunlockdevice.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuickUnlockDeviceDeleteOne is the builder for deleting a single QuickUnlockDevice entity.
type QuickUnlockDeviceDeleteOne struct {
	_d *QuickUnlockDeviceDelete
}

// Where appends a list predicates to the QuickUnlockDeviceDelete builder.
func (_d *QuickUnlockDeviceDeleteOne) Where(ps ...predicate.QuickUnlockDevice) *QuickUnlockDeviceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuickUnlockDeviceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quickunlockdevice.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuickUnlockDeviceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
