// Code generated by ent, DO NOT EDIT.

package gmailpendingimport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldID, id))
}

// ImportID applies equality check predicate on the "import_id" field. It's identical to ImportIDEQ.
func ImportID(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldImportID, v))
}

// SourceKey applies equality check predicate on the "source_key" field. It's identical to SourceKeyEQ.
func SourceKey(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSourceKey, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldMessageID, v))
}

// ThreadID applies equality check predicate on the "thread_id" field. It's identical to ThreadIDEQ.
func ThreadID(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldThreadID, v))
}

// Sender applies equality check predicate on the "sender" field. It's identical to SenderEQ.
func Sender(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSender, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSubject, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldReceivedAt, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldFilename, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldProvider, v))
}

// CandidateCount applies equality check predicate on the "candidate_count" field. It's identical to CandidateCountEQ.
func CandidateCount(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldCandidateCount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldStatus, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldUpdatedAt, v))
}

// StoredBytes applies equality check predicate on the "stored_bytes" field. It's identical to StoredBytesEQ.
func StoredBytes(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldStoredBytes, v))
}

// OutputFile applies equality check predicate on the "output_file" field. It's identical to OutputFileEQ.
func OutputFile(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldOutputFile, v))
}

// ImportIDEQ applies the EQ predicate on the "import_id" field.
func ImportIDEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldImportID, v))
}

// ImportIDNEQ applies the NEQ predicate on the "import_id" field.
func ImportIDNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldImportID, v))
}

// ImportIDIn applies the In predicate on the "import_id" field.
func ImportIDIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldImportID, vs...))
}

// ImportIDNotIn applies the NotIn predicate on the "import_id" field.
func ImportIDNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldImportID, vs...))
}

// ImportIDGT applies the GT predicate on the "import_id" field.
func ImportIDGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldImportID, v))
}

// ImportIDGTE applies the GTE predicate on the "import_id" field.
func ImportIDGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldImportID, v))
}

// ImportIDLT applies the LT predicate on the "import_id" field.
func ImportIDLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldImportID, v))
}

// ImportIDLTE applies the LTE predicate on the "import_id" field.
func ImportIDLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldImportID, v))
}

// ImportIDContains applies the Contains predicate on the "import_id" field.
func ImportIDContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldImportID, v))
}

// ImportIDHasPrefix applies the HasPrefix predicate on the "import_id" field.
func ImportIDHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldImportID, v))
}

// ImportIDHasSuffix applies the HasSuffix predicate on the "import_id" field.
func ImportIDHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldImportID, v))
}

// ImportIDIsNil applies the IsNil predicate on the "import_id" field.
func ImportIDIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldImportID))
}

// ImportIDNotNil applies the NotNil predicate on the "import_id" field.
func ImportIDNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldImportID))
}

// ImportIDEqualFold applies the EqualFold predicate on the "import_id" field.
func ImportIDEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldImportID, v))
}

// ImportIDContainsFold applies the ContainsFold predicate on the "import_id" field.
func ImportIDContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldImportID, v))
}

// SourceKeyEQ applies the EQ predicate on the "source_key" field.
func SourceKeyEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSourceKey, v))
}

// SourceKeyNEQ applies the NEQ predicate on the "source_key" field.
func SourceKeyNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldSourceKey, v))
}

// SourceKeyIn applies the In predicate on the "source_key" field.
func SourceKeyIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldSourceKey, vs...))
}

// SourceKeyNotIn applies the NotIn predicate on the "source_key" field.
func SourceKeyNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldSourceKey, vs...))
}

// SourceKeyGT applies the GT predicate on the "source_key" field.
func SourceKeyGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldSourceKey, v))
}

// SourceKeyGTE applies the GTE predicate on the "source_key" field.
func SourceKeyGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldSourceKey, v))
}

// SourceKeyLT applies the LT predicate on the "source_key" field.
func SourceKeyLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldSourceKey, v))
}

// SourceKeyLTE applies the LTE predicate on the "source_key" field.
func SourceKeyLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldSourceKey, v))
}

// SourceKeyContains applies the Contains predicate on the "source_key" field.
func SourceKeyContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldSourceKey, v))
}

// SourceKeyHasPrefix applies the HasPrefix predicate on the "source_key" field.
func SourceKeyHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldSourceKey, v))
}

// SourceKeyHasSuffix applies the HasSuffix predicate on the "source_key" field.
func SourceKeyHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldSourceKey, v))
}

// SourceKeyIsNil applies the IsNil predicate on the "source_key" field.
func SourceKeyIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldSourceKey))
}

// SourceKeyNotNil applies the NotNil predicate on the "source_key" field.
func SourceKeyNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldSourceKey))
}

// SourceKeyEqualFold applies the EqualFold predicate on the "source_key" field.
func SourceKeyEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldSourceKey, v))
}

// SourceKeyContainsFold applies the ContainsFold predicate on the "source_key" field.
func SourceKeyContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldSourceKey, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldMessageID, v))
}

// MessageIDContains applies the Contains predicate on the "message_id" field.
func MessageIDContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldMessageID, v))
}

// MessageIDHasPrefix applies the HasPrefix predicate on the "message_id" field.
func MessageIDHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldMessageID, v))
}

// MessageIDHasSuffix applies the HasSuffix predicate on the "message_id" field.
func MessageIDHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldMessageID, v))
}

// MessageIDEqualFold applies the EqualFold predicate on the "message_id" field.
func MessageIDEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldMessageID, v))
}

// MessageIDContainsFold applies the ContainsFold predicate on the "message_id" field.
func MessageIDContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldMessageID, v))
}

// ThreadIDEQ applies the EQ predicate on the "thread_id" field.
func ThreadIDEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldThreadID, v))
}

// ThreadIDNEQ applies the NEQ predicate on the "thread_id" field.
func ThreadIDNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldThreadID, v))
}

// ThreadIDIn applies the In predicate on the "thread_id" field.
func ThreadIDIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldThreadID, vs...))
}

// ThreadIDNotIn applies the NotIn predicate on the "thread_id" field.
func ThreadIDNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldThreadID, vs...))
}

// ThreadIDGT applies the GT predicate on the "thread_id" field.
func ThreadIDGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldThreadID, v))
}

// ThreadIDGTE applies the GTE predicate on the "thread_id" field.
func ThreadIDGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldThreadID, v))
}

// ThreadIDLT applies the LT predicate on the "thread_id" field.
func ThreadIDLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldThreadID, v))
}

// ThreadIDLTE applies the LTE predicate on the "thread_id" field.
func ThreadIDLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldThreadID, v))
}

// ThreadIDContains applies the Contains predicate on the "thread_id" field.
func ThreadIDContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldThreadID, v))
}

// ThreadIDHasPrefix applies the HasPrefix predicate on the "thread_id" field.
func ThreadIDHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldThreadID, v))
}

// ThreadIDHasSuffix applies the HasSuffix predicate on the "thread_id" field.
func ThreadIDHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldThreadID, v))
}

// ThreadIDIsNil applies the IsNil predicate on the "thread_id" field.
func ThreadIDIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldThreadID))
}

// ThreadIDNotNil applies the NotNil predicate on the "thread_id" field.
func ThreadIDNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldThreadID))
}

// ThreadIDEqualFold applies the EqualFold predicate on the "thread_id" field.
func ThreadIDEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldThreadID, v))
}

// ThreadIDContainsFold applies the ContainsFold predicate on the "thread_id" field.
func ThreadIDContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldThreadID, v))
}

// SenderEQ applies the EQ predicate on the "sender" field.
func SenderEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSender, v))
}

// SenderNEQ applies the NEQ predicate on the "sender" field.
func SenderNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldSender, v))
}

// SenderIn applies the In predicate on the "sender" field.
func SenderIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldSender, vs...))
}

// SenderNotIn applies the NotIn predicate on the "sender" field.
func SenderNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldSender, vs...))
}

// SenderGT applies the GT predicate on the "sender" field.
func SenderGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldSender, v))
}

// SenderGTE applies the GTE predicate on the "sender" field.
func SenderGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldSender, v))
}

// SenderLT applies the LT predicate on the "sender" field.
func SenderLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldSender, v))
}

// SenderLTE applies the LTE predicate on the "sender" field.
func SenderLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldSender, v))
}

// SenderContains applies the Contains predicate on the "sender" field.
func SenderContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldSender, v))
}

// SenderHasPrefix applies the HasPrefix predicate on the "sender" field.
func SenderHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldSender, v))
}

// SenderHasSuffix applies the HasSuffix predicate on the "sender" field.
func SenderHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldSender, v))
}

// SenderEqualFold applies the EqualFold predicate on the "sender" field.
func SenderEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldSender, v))
}

// SenderContainsFold applies the ContainsFold predicate on the "sender" field.
func SenderContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldSender, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldSubject, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldReceivedAt, v))
}

// ReceivedAtIsNil applies the IsNil predicate on the "received_at" field.
func ReceivedAtIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldReceivedAt))
}

// ReceivedAtNotNil applies the NotNil predicate on the "received_at" field.
func ReceivedAtNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldReceivedAt))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldFilename, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldProvider, v))
}

// CandidateCountEQ applies the EQ predicate on the "candidate_count" field.
func CandidateCountEQ(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldCandidateCount, v))
}

// CandidateCountNEQ applies the NEQ predicate on the "candidate_count" field.
func CandidateCountNEQ(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldCandidateCount, v))
}

// CandidateCountIn applies the In predicate on the "candidate_count" field.
func CandidateCountIn(vs ...int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldCandidateCount, vs...))
}

// CandidateCountNotIn applies the NotIn predicate on the "candidate_count" field.
func CandidateCountNotIn(vs ...int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldCandidateCount, vs...))
}

// CandidateCountGT applies the GT predicate on the "candidate_count" field.
func CandidateCountGT(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldCandidateCount, v))
}

// CandidateCountGTE applies the GTE predicate on the "candidate_count" field.
func CandidateCountGTE(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldCandidateCount, v))
}

// CandidateCountLT applies the LT predicate on the "candidate_count" field.
func CandidateCountLT(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldCandidateCount, v))
}

// CandidateCountLTE applies the LTE predicate on the "candidate_count" field.
func CandidateCountLTE(v int) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldCandidateCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldUpdatedAt, v))
}

// StoredBytesEQ applies the EQ predicate on the "stored_bytes" field.
func StoredBytesEQ(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldStoredBytes, v))
}

// StoredBytesNEQ applies the NEQ predicate on the "stored_bytes" field.
func StoredBytesNEQ(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldStoredBytes, v))
}

// StoredBytesIn applies the In predicate on the "stored_bytes" field.
func StoredBytesIn(vs ...int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldStoredBytes, vs...))
}

// StoredBytesNotIn applies the NotIn predicate on the "stored_bytes" field.
func StoredBytesNotIn(vs ...int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldStoredBytes, vs...))
}

// StoredBytesGT applies the GT predicate on the "stored_bytes" field.
func StoredBytesGT(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldStoredBytes, v))
}

// StoredBytesGTE applies the GTE predicate on the "stored_bytes" field.
func StoredBytesGTE(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldStoredBytes, v))
}

// StoredBytesLT applies the LT predicate on the "stored_bytes" field.
func StoredBytesLT(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldStoredBytes, v))
}

// StoredBytesLTE applies the LTE predicate on the "stored_bytes" field.
func StoredBytesLTE(v int64) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldStoredBytes, v))
}

// OutputFileEQ applies the EQ predicate on the "output_file" field.
func OutputFileEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEQ(FieldOutputFile, v))
}

// OutputFileNEQ applies the NEQ predicate on the "output_file" field.
func OutputFileNEQ(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNEQ(FieldOutputFile, v))
}

// OutputFileIn applies the In predicate on the "output_file" field.
func OutputFileIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIn(FieldOutputFile, vs...))
}

// OutputFileNotIn applies the NotIn predicate on the "output_file" field.
func OutputFileNotIn(vs ...string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotIn(FieldOutputFile, vs...))
}

// OutputFileGT applies the GT predicate on the "output_file" field.
func OutputFileGT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGT(FieldOutputFile, v))
}

// OutputFileGTE applies the GTE predicate on the "output_file" field.
func OutputFileGTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldGTE(FieldOutputFile, v))
}

// OutputFileLT applies the LT predicate on the "output_file" field.
func OutputFileLT(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLT(FieldOutputFile, v))
}

// OutputFileLTE applies the LTE predicate on the "output_file" field.
func OutputFileLTE(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldLTE(FieldOutputFile, v))
}

// OutputFileContains applies the Contains predicate on the "output_file" field.
func OutputFileContains(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContains(FieldOutputFile, v))
}

// OutputFileHasPrefix applies the HasPrefix predicate on the "output_file" field.
func OutputFileHasPrefix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasPrefix(FieldOutputFile, v))
}

// OutputFileHasSuffix applies the HasSuffix predicate on the "output_file" field.
func OutputFileHasSuffix(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldHasSuffix(FieldOutputFile, v))
}

// OutputFileIsNil applies the IsNil predicate on the "output_file" field.
func OutputFileIsNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldIsNull(FieldOutputFile))
}

// OutputFileNotNil applies the NotNil predicate on the "output_file" field.
func OutputFileNotNil() predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldNotNull(FieldOutputFile))
}

// OutputFileEqualFold applies the EqualFold predicate on the "output_file" field.
func OutputFileEqualFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldEqualFold(FieldOutputFile, v))
}

// OutputFileContainsFold applies the ContainsFold predicate on the "output_file" field.
func OutputFileContainsFold(v string) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.FieldContainsFold(FieldOutputFile, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GmailPendingImport) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GmailPendingImport) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GmailPendingImport) predicate.GmailPendingImport {
	return predicate.GmailPendingImport(sql.NotPredicates(p))
}
