// Code generated by ent, DO NOT EDIT.

package agentapproval

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentapproval type in the database.
	Label = "agent_approval"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClusterID holds the string denoting the cluster_id field in the database.
	FieldClusterID = "cluster_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldToolCallID holds the string denoting the tool_call_id field in the database.
	FieldToolCallID = "tool_call_id"
	// FieldToolName holds the string denoting the tool_name field in the database.
	FieldToolName = "tool_name"
	// FieldToolTitle holds the string denoting the tool_title field in the database.
	FieldToolTitle = "tool_title"
	// FieldArguments holds the string denoting the arguments field in the database.
	FieldArguments = "arguments"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldPage holds the string denoting the page field in the database.
	FieldPage = "page"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldRangeStart holds the string denoting the range_start field in the database.
	FieldRangeStart = "range_start"
	// FieldRangeEnd holds the string denoting the range_end field in the database.
	FieldRangeEnd = "range_end"
	// FieldValuationCurrency holds the string denoting the valuation_currency field in the database.
	FieldValuationCurrency = "valuation_currency"
	// FieldBqlQuery holds the string denoting the bql_query field in the database.
	FieldBqlQuery = "bql_query"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the agentapproval in the database.
	Table = "agent_approvals"
)

// Columns holds all SQL columns for agentapproval fields.
var Columns = []string{
	FieldID,
	FieldClusterID,
	FieldSessionID,
	FieldToolCallID,
	FieldToolName,
	FieldToolTitle,
	FieldArguments,
	FieldSummary,
	FieldPage,
	FieldPath,
	FieldRangeStart,
	FieldRangeEnd,
	FieldValuationCurrency,
	FieldBqlQuery,
	FieldCreatedAt,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AgentApproval queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClusterID orders the results by the cluster_id field.
func ByClusterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClusterID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByToolCallID orders the results by the tool_call_id field.
func ByToolCallID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolCallID, opts...).ToFunc()
}

// ByToolName orders the results by the tool_name field.
func ByToolName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolName, opts...).ToFunc()
}

// ByToolTitle orders the results by the tool_title field.
func ByToolTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolTitle, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByPage orders the results by the page field.
func ByPage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPage, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByRangeStart orders the results by the range_start field.
func ByRangeStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRangeStart, opts...).ToFunc()
}

// ByRangeEnd orders the results by the range_end field.
func ByRangeEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRangeEnd, opts...).ToFunc()
}

// ByValuationCurrency orders the results by the valuation_currency field.
func ByValuationCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValuationCurrency, opts...).ToFunc()
}

// ByBqlQuery orders the results by the bql_query field.
func ByBqlQuery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBqlQuery, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
