// Code generated by ent, DO NOT EDIT.

package agentapproval

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldID, id))
}

// ClusterID applies equality check predicate on the "cluster_id" field. It's identical to ClusterIDEQ.
func ClusterID(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldClusterID, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldSessionID, v))
}

// ToolCallID applies equality check predicate on the "tool_call_id" field. It's identical to ToolCallIDEQ.
func ToolCallID(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolCallID, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolName, v))
}

// ToolTitle applies equality check predicate on the "tool_title" field. It's identical to ToolTitleEQ.
func ToolTitle(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolTitle, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldSummary, v))
}

// Page applies equality check predicate on the "page" field. It's identical to PageEQ.
func Page(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldPage, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldPath, v))
}

// RangeStart applies equality check predicate on the "range_start" field. It's identical to RangeStartEQ.
func RangeStart(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldRangeStart, v))
}

// RangeEnd applies equality check predicate on the "range_end" field. It's identical to RangeEndEQ.
func RangeEnd(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldRangeEnd, v))
}

// ValuationCurrency applies equality check predicate on the "valuation_currency" field. It's identical to ValuationCurrencyEQ.
func ValuationCurrency(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldValuationCurrency, v))
}

// BqlQuery applies equality check predicate on the "bql_query" field. It's identical to BqlQueryEQ.
func BqlQuery(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldBqlQuery, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldExpiresAt, v))
}

// ClusterIDEQ applies the EQ predicate on the "cluster_id" field.
func ClusterIDEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldClusterID, v))
}

// ClusterIDNEQ applies the NEQ predicate on the "cluster_id" field.
func ClusterIDNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldClusterID, v))
}

// ClusterIDIn applies the In predicate on the "cluster_id" field.
func ClusterIDIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldClusterID, vs...))
}

// ClusterIDNotIn applies the NotIn predicate on the "cluster_id" field.
func ClusterIDNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldClusterID, vs...))
}

// ClusterIDGT applies the GT predicate on the "cluster_id" field.
func ClusterIDGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldClusterID, v))
}

// ClusterIDGTE applies the GTE predicate on the "cluster_id" field.
func ClusterIDGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldClusterID, v))
}

// ClusterIDLT applies the LT predicate on the "cluster_id" field.
func ClusterIDLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldClusterID, v))
}

// ClusterIDLTE applies the LTE predicate on the "cluster_id" field.
func ClusterIDLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldClusterID, v))
}

// ClusterIDContains applies the Contains predicate on the "cluster_id" field.
func ClusterIDContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldClusterID, v))
}

// ClusterIDHasPrefix applies the HasPrefix predicate on the "cluster_id" field.
func ClusterIDHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldClusterID, v))
}

// ClusterIDHasSuffix applies the HasSuffix predicate on the "cluster_id" field.
func ClusterIDHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldClusterID, v))
}

// ClusterIDEqualFold applies the EqualFold predicate on the "cluster_id" field.
func ClusterIDEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldClusterID, v))
}

// ClusterIDContainsFold applies the ContainsFold predicate on the "cluster_id" field.
func ClusterIDContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldClusterID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldSessionID, v))
}

// ToolCallIDEQ applies the EQ predicate on the "tool_call_id" field.
func ToolCallIDEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolCallID, v))
}

// ToolCallIDNEQ applies the NEQ predicate on the "tool_call_id" field.
func ToolCallIDNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldToolCallID, v))
}

// ToolCallIDIn applies the In predicate on the "tool_call_id" field.
func ToolCallIDIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldToolCallID, vs...))
}

// ToolCallIDNotIn applies the NotIn predicate on the "tool_call_id" field.
func ToolCallIDNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldToolCallID, vs...))
}

// ToolCallIDGT applies the GT predicate on the "tool_call_id" field.
func ToolCallIDGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldToolCallID, v))
}

// ToolCallIDGTE applies the GTE predicate on the "tool_call_id" field.
func ToolCallIDGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldToolCallID, v))
}

// ToolCallIDLT applies the LT predicate on the "tool_call_id" field.
func ToolCallIDLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldToolCallID, v))
}

// ToolCallIDLTE applies the LTE predicate on the "tool_call_id" field.
func ToolCallIDLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldToolCallID, v))
}

// ToolCallIDContains applies the Contains predicate on the "tool_call_id" field.
func ToolCallIDContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldToolCallID, v))
}

// ToolCallIDHasPrefix applies the HasPrefix predicate on the "tool_call_id" field.
func ToolCallIDHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldToolCallID, v))
}

// ToolCallIDHasSuffix applies the HasSuffix predicate on the "tool_call_id" field.
func ToolCallIDHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldToolCallID, v))
}

// ToolCallIDEqualFold applies the EqualFold predicate on the "tool_call_id" field.
func ToolCallIDEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldToolCallID, v))
}

// ToolCallIDContainsFold applies the ContainsFold predicate on the "tool_call_id" field.
func ToolCallIDContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldToolCallID, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldToolName, v))
}

// ToolTitleEQ applies the EQ predicate on the "tool_title" field.
func ToolTitleEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldToolTitle, v))
}

// ToolTitleNEQ applies the NEQ predicate on the "tool_title" field.
func ToolTitleNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldToolTitle, v))
}

// ToolTitleIn applies the In predicate on the "tool_title" field.
func ToolTitleIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldToolTitle, vs...))
}

// ToolTitleNotIn applies the NotIn predicate on the "tool_title" field.
func ToolTitleNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldToolTitle, vs...))
}

// ToolTitleGT applies the GT predicate on the "tool_title" field.
func ToolTitleGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldToolTitle, v))
}

// ToolTitleGTE applies the GTE predicate on the "tool_title" field.
func ToolTitleGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldToolTitle, v))
}

// ToolTitleLT applies the LT predicate on the "tool_title" field.
func ToolTitleLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldToolTitle, v))
}

// ToolTitleLTE applies the LTE predicate on the "tool_title" field.
func ToolTitleLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldToolTitle, v))
}

// ToolTitleContains applies the Contains predicate on the "tool_title" field.
func ToolTitleContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldToolTitle, v))
}

// ToolTitleHasPrefix applies the HasPrefix predicate on the "tool_title" field.
func ToolTitleHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldToolTitle, v))
}

// ToolTitleHasSuffix applies the HasSuffix predicate on the "tool_title" field.
func ToolTitleHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldToolTitle, v))
}

// ToolTitleEqualFold applies the EqualFold predicate on the "tool_title" field.
func ToolTitleEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldToolTitle, v))
}

// ToolTitleContainsFold applies the ContainsFold predicate on the "tool_title" field.
func ToolTitleContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldToolTitle, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldSummary, v))
}

// PageEQ applies the EQ predicate on the "page" field.
func PageEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldPage, v))
}

// PageNEQ applies the NEQ predicate on the "page" field.
func PageNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldPage, v))
}

// PageIn applies the In predicate on the "page" field.
func PageIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldPage, vs...))
}

// PageNotIn applies the NotIn predicate on the "page" field.
func PageNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldPage, vs...))
}

// PageGT applies the GT predicate on the "page" field.
func PageGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldPage, v))
}

// PageGTE applies the GTE predicate on the "page" field.
func PageGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldPage, v))
}

// PageLT applies the LT predicate on the "page" field.
func PageLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldPage, v))
}

// PageLTE applies the LTE predicate on the "page" field.
func PageLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldPage, v))
}

// PageContains applies the Contains predicate on the "page" field.
func PageContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldPage, v))
}

// PageHasPrefix applies the HasPrefix predicate on the "page" field.
func PageHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldPage, v))
}

// PageHasSuffix applies the HasSuffix predicate on the "page" field.
func PageHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldPage, v))
}

// PageIsNil applies the IsNil predicate on the "page" field.
func PageIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldPage))
}

// PageNotNil applies the NotNil predicate on the "page" field.
func PageNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldPage))
}

// PageEqualFold applies the EqualFold predicate on the "page" field.
func PageEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldPage, v))
}

// PageContainsFold applies the ContainsFold predicate on the "page" field.
func PageContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldPage, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldPath, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldPath))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldPath, v))
}

// RangeStartEQ applies the EQ predicate on the "range_start" field.
func RangeStartEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldRangeStart, v))
}

// RangeStartNEQ applies the NEQ predicate on the "range_start" field.
func RangeStartNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldRangeStart, v))
}

// RangeStartIn applies the In predicate on the "range_start" field.
func RangeStartIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldRangeStart, vs...))
}

// RangeStartNotIn applies the NotIn predicate on the "range_start" field.
func RangeStartNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldRangeStart, vs...))
}

// RangeStartGT applies the GT predicate on the "range_start" field.
func RangeStartGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldRangeStart, v))
}

// RangeStartGTE applies the GTE predicate on the "range_start" field.
func RangeStartGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldRangeStart, v))
}

// RangeStartLT applies the LT predicate on the "range_start" field.
func RangeStartLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldRangeStart, v))
}

// RangeStartLTE applies the LTE predicate on the "range_start" field.
func RangeStartLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldRangeStart, v))
}

// RangeStartContains applies the Contains predicate on the "range_start" field.
func RangeStartContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldRangeStart, v))
}

// RangeStartHasPrefix applies the HasPrefix predicate on the "range_start" field.
func RangeStartHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldRangeStart, v))
}

// RangeStartHasSuffix applies the HasSuffix predicate on the "range_start" field.
func RangeStartHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldRangeStart, v))
}

// RangeStartIsNil applies the IsNil predicate on the "range_start" field.
func RangeStartIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldRangeStart))
}

// RangeStartNotNil applies the NotNil predicate on the "range_start" field.
func RangeStartNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldRangeStart))
}

// RangeStartEqualFold applies the EqualFold predicate on the "range_start" field.
func RangeStartEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldRangeStart, v))
}

// RangeStartContainsFold applies the ContainsFold predicate on the "range_start" field.
func RangeStartContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldRangeStart, v))
}

// RangeEndEQ applies the EQ predicate on the "range_end" field.
func RangeEndEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldRangeEnd, v))
}

// RangeEndNEQ applies the NEQ predicate on the "range_end" field.
func RangeEndNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldRangeEnd, v))
}

// RangeEndIn applies the In predicate on the "range_end" field.
func RangeEndIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldRangeEnd, vs...))
}

// RangeEndNotIn applies the NotIn predicate on the "range_end" field.
func RangeEndNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldRangeEnd, vs...))
}

// RangeEndGT applies the GT predicate on the "range_end" field.
func RangeEndGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldRangeEnd, v))
}

// RangeEndGTE applies the GTE predicate on the "range_end" field.
func RangeEndGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldRangeEnd, v))
}

// RangeEndLT applies the LT predicate on the "range_end" field.
func RangeEndLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldRangeEnd, v))
}

// RangeEndLTE applies the LTE predicate on the "range_end" field.
func RangeEndLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldRangeEnd, v))
}

// RangeEndContains applies the Contains predicate on the "range_end" field.
func RangeEndContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldRangeEnd, v))
}

// RangeEndHasPrefix applies the HasPrefix predicate on the "range_end" field.
func RangeEndHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldRangeEnd, v))
}

// RangeEndHasSuffix applies the HasSuffix predicate on the "range_end" field.
func RangeEndHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldRangeEnd, v))
}

// RangeEndIsNil applies the IsNil predicate on the "range_end" field.
func RangeEndIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldRangeEnd))
}

// RangeEndNotNil applies the NotNil predicate on the "range_end" field.
func RangeEndNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldRangeEnd))
}

// RangeEndEqualFold applies the EqualFold predicate on the "range_end" field.
func RangeEndEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldRangeEnd, v))
}

// RangeEndContainsFold applies the ContainsFold predicate on the "range_end" field.
func RangeEndContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldRangeEnd, v))
}

// ValuationCurrencyEQ applies the EQ predicate on the "valuation_currency" field.
func ValuationCurrencyEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldValuationCurrency, v))
}

// ValuationCurrencyNEQ applies the NEQ predicate on the "valuation_currency" field.
func ValuationCurrencyNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldValuationCurrency, v))
}

// ValuationCurrencyIn applies the In predicate on the "valuation_currency" field.
func ValuationCurrencyIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldValuationCurrency, vs...))
}

// ValuationCurrencyNotIn applies the NotIn predicate on the "valuation_currency" field.
func ValuationCurrencyNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldValuationCurrency, vs...))
}

// ValuationCurrencyGT applies the GT predicate on the "valuation_currency" field.
func ValuationCurrencyGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldValuationCurrency, v))
}

// ValuationCurrencyGTE applies the GTE predicate on the "valuation_currency" field.
func ValuationCurrencyGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldValuationCurrency, v))
}

// ValuationCurrencyLT applies the LT predicate on the "valuation_currency" field.
func ValuationCurrencyLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldValuationCurrency, v))
}

// ValuationCurrencyLTE applies the LTE predicate on the "valuation_currency" field.
func ValuationCurrencyLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldValuationCurrency, v))
}

// ValuationCurrencyContains applies the Contains predicate on the "valuation_currency" field.
func ValuationCurrencyContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldValuationCurrency, v))
}

// ValuationCurrencyHasPrefix applies the HasPrefix predicate on the "valuation_currency" field.
func ValuationCurrencyHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldValuationCurrency, v))
}

// ValuationCurrencyHasSuffix applies the HasSuffix predicate on the "valuation_currency" field.
func ValuationCurrencyHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldValuationCurrency, v))
}

// ValuationCurrencyIsNil applies the IsNil predicate on the "valuation_currency" field.
func ValuationCurrencyIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldValuationCurrency))
}

// ValuationCurrencyNotNil applies the NotNil predicate on the "valuation_currency" field.
func ValuationCurrencyNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldValuationCurrency))
}

// ValuationCurrencyEqualFold applies the EqualFold predicate on the "valuation_currency" field.
func ValuationCurrencyEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldValuationCurrency, v))
}

// ValuationCurrencyContainsFold applies the ContainsFold predicate on the "valuation_currency" field.
func ValuationCurrencyContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldValuationCurrency, v))
}

// BqlQueryEQ applies the EQ predicate on the "bql_query" field.
func BqlQueryEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldBqlQuery, v))
}

// BqlQueryNEQ applies the NEQ predicate on the "bql_query" field.
func BqlQueryNEQ(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldBqlQuery, v))
}

// BqlQueryIn applies the In predicate on the "bql_query" field.
func BqlQueryIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldBqlQuery, vs...))
}

// BqlQueryNotIn applies the NotIn predicate on the "bql_query" field.
func BqlQueryNotIn(vs ...string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldBqlQuery, vs...))
}

// BqlQueryGT applies the GT predicate on the "bql_query" field.
func BqlQueryGT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldBqlQuery, v))
}

// BqlQueryGTE applies the GTE predicate on the "bql_query" field.
func BqlQueryGTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldBqlQuery, v))
}

// BqlQueryLT applies the LT predicate on the "bql_query" field.
func BqlQueryLT(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldBqlQuery, v))
}

// BqlQueryLTE applies the LTE predicate on the "bql_query" field.
func BqlQueryLTE(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldBqlQuery, v))
}

// BqlQueryContains applies the Contains predicate on the "bql_query" field.
func BqlQueryContains(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContains(FieldBqlQuery, v))
}

// BqlQueryHasPrefix applies the HasPrefix predicate on the "bql_query" field.
func BqlQueryHasPrefix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasPrefix(FieldBqlQuery, v))
}

// BqlQueryHasSuffix applies the HasSuffix predicate on the "bql_query" field.
func BqlQueryHasSuffix(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldHasSuffix(FieldBqlQuery, v))
}

// BqlQueryIsNil applies the IsNil predicate on the "bql_query" field.
func BqlQueryIsNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIsNull(FieldBqlQuery))
}

// BqlQueryNotNil applies the NotNil predicate on the "bql_query" field.
func BqlQueryNotNil() predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotNull(FieldBqlQuery))
}

// BqlQueryEqualFold applies the EqualFold predicate on the "bql_query" field.
func BqlQueryEqualFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEqualFold(FieldBqlQuery, v))
}

// BqlQueryContainsFold applies the ContainsFold predicate on the "bql_query" field.
func BqlQueryContainsFold(v string) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldContainsFold(FieldBqlQuery, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AgentApproval {
	return predicate.AgentApproval(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentApproval) predicate.AgentApproval {
	return predicate.AgentApproval(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentApproval) predicate.AgentApproval {
	return predicate.AgentApproval(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentApproval) predicate.AgentApproval {
	return predicate.AgentApproval(sql.NotPredicates(p))
}
