// Code generated by ent, DO NOT EDIT.

package importpreviewwarning

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the importpreviewwarning type in the database.
	Label = "import_preview_warning"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImportID holds the string denoting the import_id field in the database.
	FieldImportID = "import_id"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// Table holds the table name of the importpreviewwarning in the database.
	Table = "import_preview_warnings"
)

// Columns holds all SQL columns for importpreviewwarning fields.
var Columns = []string{
	FieldID,
	FieldImportID,
	FieldPosition,
	FieldMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ImportPreviewWarning queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImportID orders the results by the import_id field.
func ByImportID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportID, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}
