// Code generated by ent, DO NOT EDIT.

package webpushsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContainsFold(FieldID, id))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldEndpoint, v))
}

// ExpirationTime applies equality check predicate on the "expiration_time" field. It's identical to ExpirationTimeEQ.
func ExpirationTime(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldExpirationTime, v))
}

// AuthSecret applies equality check predicate on the "auth_secret" field. It's identical to AuthSecretEQ.
func AuthSecret(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldAuthSecret, v))
}

// P256dh applies equality check predicate on the "p256dh" field. It's identical to P256dhEQ.
func P256dh(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldP256dh, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldUserAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContainsFold(FieldEndpoint, v))
}

// ExpirationTimeEQ applies the EQ predicate on the "expiration_time" field.
func ExpirationTimeEQ(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldExpirationTime, v))
}

// ExpirationTimeNEQ applies the NEQ predicate on the "expiration_time" field.
func ExpirationTimeNEQ(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldExpirationTime, v))
}

// ExpirationTimeIn applies the In predicate on the "expiration_time" field.
func ExpirationTimeIn(vs ...float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldExpirationTime, vs...))
}

// ExpirationTimeNotIn applies the NotIn predicate on the "expiration_time" field.
func ExpirationTimeNotIn(vs ...float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldExpirationTime, vs...))
}

// ExpirationTimeGT applies the GT predicate on the "expiration_time" field.
func ExpirationTimeGT(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldExpirationTime, v))
}

// ExpirationTimeGTE applies the GTE predicate on the "expiration_time" field.
func ExpirationTimeGTE(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldExpirationTime, v))
}

// ExpirationTimeLT applies the LT predicate on the "expiration_time" field.
func ExpirationTimeLT(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldExpirationTime, v))
}

// ExpirationTimeLTE applies the LTE predicate on the "expiration_time" field.
func ExpirationTimeLTE(v float64) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldExpirationTime, v))
}

// ExpirationTimeIsNil applies the IsNil predicate on the "expiration_time" field.
func ExpirationTimeIsNil() predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIsNull(FieldExpirationTime))
}

// ExpirationTimeNotNil applies the NotNil predicate on the "expiration_time" field.
func ExpirationTimeNotNil() predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotNull(FieldExpirationTime))
}

// AuthSecretEQ applies the EQ predicate on the "auth_secret" field.
func AuthSecretEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldAuthSecret, v))
}

// AuthSecretNEQ applies the NEQ predicate on the "auth_secret" field.
func AuthSecretNEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldAuthSecret, v))
}

// AuthSecretIn applies the In predicate on the "auth_secret" field.
func AuthSecretIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldAuthSecret, vs...))
}

// AuthSecretNotIn applies the NotIn predicate on the "auth_secret" field.
func AuthSecretNotIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldAuthSecret, vs...))
}

// AuthSecretGT applies the GT predicate on the "auth_secret" field.
func AuthSecretGT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldAuthSecret, v))
}

// AuthSecretGTE applies the GTE predicate on the "auth_secret" field.
func AuthSecretGTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldAuthSecret, v))
}

// AuthSecretLT applies the LT predicate on the "auth_secret" field.
func AuthSecretLT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldAuthSecret, v))
}

// AuthSecretLTE applies the LTE predicate on the "auth_secret" field.
func AuthSecretLTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldAuthSecret, v))
}

// AuthSecretContains applies the Contains predicate on the "auth_secret" field.
func AuthSecretContains(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContains(FieldAuthSecret, v))
}

// AuthSecretHasPrefix applies the HasPrefix predicate on the "auth_secret" field.
func AuthSecretHasPrefix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasPrefix(FieldAuthSecret, v))
}

// AuthSecretHasSuffix applies the HasSuffix predicate on the "auth_secret" field.
func AuthSecretHasSuffix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasSuffix(FieldAuthSecret, v))
}

// AuthSecretEqualFold applies the EqualFold predicate on the "auth_secret" field.
func AuthSecretEqualFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEqualFold(FieldAuthSecret, v))
}

// AuthSecretContainsFold applies the ContainsFold predicate on the "auth_secret" field.
func AuthSecretContainsFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContainsFold(FieldAuthSecret, v))
}

// P256dhEQ applies the EQ predicate on the "p256dh" field.
func P256dhEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldP256dh, v))
}

// P256dhNEQ applies the NEQ predicate on the "p256dh" field.
func P256dhNEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldP256dh, v))
}

// P256dhIn applies the In predicate on the "p256dh" field.
func P256dhIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldP256dh, vs...))
}

// P256dhNotIn applies the NotIn predicate on the "p256dh" field.
func P256dhNotIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldP256dh, vs...))
}

// P256dhGT applies the GT predicate on the "p256dh" field.
func P256dhGT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldP256dh, v))
}

// P256dhGTE applies the GTE predicate on the "p256dh" field.
func P256dhGTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldP256dh, v))
}

// P256dhLT applies the LT predicate on the "p256dh" field.
func P256dhLT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldP256dh, v))
}

// P256dhLTE applies the LTE predicate on the "p256dh" field.
func P256dhLTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldP256dh, v))
}

// P256dhContains applies the Contains predicate on the "p256dh" field.
func P256dhContains(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContains(FieldP256dh, v))
}

// P256dhHasPrefix applies the HasPrefix predicate on the "p256dh" field.
func P256dhHasPrefix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasPrefix(FieldP256dh, v))
}

// P256dhHasSuffix applies the HasSuffix predicate on the "p256dh" field.
func P256dhHasSuffix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasSuffix(FieldP256dh, v))
}

// P256dhEqualFold applies the EqualFold predicate on the "p256dh" field.
func P256dhEqualFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEqualFold(FieldP256dh, v))
}

// P256dhContainsFold applies the ContainsFold predicate on the "p256dh" field.
func P256dhContainsFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContainsFold(FieldP256dh, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldContainsFold(FieldUserAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebPushSubscription) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebPushSubscription) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebPushSubscription) predicate.WebPushSubscription {
	return predicate.WebPushSubscription(sql.NotPredicates(p))
}
