// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent"
)

// The AgentApprovalFunc type is an adapter to allow the use of ordinary
// function as AgentApproval mutator.
type AgentApprovalFunc func(context.Context, *ent.AgentApprovalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentApprovalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentApprovalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentApprovalMutation", m)
}

// The AgentMemoryFunc type is an adapter to allow the use of ordinary
// function as AgentMemory mutator.
type AgentMemoryFunc func(context.Context, *ent.AgentMemoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentMemoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentMemoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentMemoryMutation", m)
}

// The AgentSessionFunc type is an adapter to allow the use of ordinary
// function as AgentSession mutator.
type AgentSessionFunc func(context.Context, *ent.AgentSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentSessionMutation", m)
}

// The AgentSessionMessageFunc type is an adapter to allow the use of ordinary
// function as AgentSessionMessage mutator.
type AgentSessionMessageFunc func(context.Context, *ent.AgentSessionMessageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentSessionMessageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentSessionMessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentSessionMessageMutation", m)
}

// The BQLHistoryRecordFunc type is an adapter to allow the use of ordinary
// function as BQLHistoryRecord mutator.
type BQLHistoryRecordFunc func(context.Context, *ent.BQLHistoryRecordMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BQLHistoryRecordFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BQLHistoryRecordMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BQLHistoryRecordMutation", m)
}

// The GmailConnectionFunc type is an adapter to allow the use of ordinary
// function as GmailConnection mutator.
type GmailConnectionFunc func(context.Context, *ent.GmailConnectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GmailConnectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GmailConnectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GmailConnectionMutation", m)
}

// The GmailOAuthStateFunc type is an adapter to allow the use of ordinary
// function as GmailOAuthState mutator.
type GmailOAuthStateFunc func(context.Context, *ent.GmailOAuthStateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GmailOAuthStateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GmailOAuthStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GmailOAuthStateMutation", m)
}

// The GmailPendingImportFunc type is an adapter to allow the use of ordinary
// function as GmailPendingImport mutator.
type GmailPendingImportFunc func(context.Context, *ent.GmailPendingImportMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GmailPendingImportFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GmailPendingImportMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GmailPendingImportMutation", m)
}

// The GmailPushEventFunc type is an adapter to allow the use of ordinary
// function as GmailPushEvent mutator.
type GmailPushEventFunc func(context.Context, *ent.GmailPushEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GmailPushEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GmailPushEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GmailPushEventMutation", m)
}

// The GmailSyncLeaseFunc type is an adapter to allow the use of ordinary
// function as GmailSyncLease mutator.
type GmailSyncLeaseFunc func(context.Context, *ent.GmailSyncLeaseMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GmailSyncLeaseFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GmailSyncLeaseMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GmailSyncLeaseMutation", m)
}

// The ImportJobFunc type is an adapter to allow the use of ordinary
// function as ImportJob mutator.
type ImportJobFunc func(context.Context, *ent.ImportJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ImportJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ImportJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ImportJobMutation", m)
}

// The ImportPreviewStateFunc type is an adapter to allow the use of ordinary
// function as ImportPreviewState mutator.
type ImportPreviewStateFunc func(context.Context, *ent.ImportPreviewStateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ImportPreviewStateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ImportPreviewStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ImportPreviewStateMutation", m)
}

// The ImportPreviewWarningFunc type is an adapter to allow the use of ordinary
// function as ImportPreviewWarning mutator.
type ImportPreviewWarningFunc func(context.Context, *ent.ImportPreviewWarningMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ImportPreviewWarningFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ImportPreviewWarningMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ImportPreviewWarningMutation", m)
}

// The NotificationFunc type is an adapter to allow the use of ordinary
// function as Notification mutator.
type NotificationFunc func(context.Context, *ent.NotificationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NotificationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NotificationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NotificationMutation", m)
}

// The PasskeyCredentialFunc type is an adapter to allow the use of ordinary
// function as PasskeyCredential mutator.
type PasskeyCredentialFunc func(context.Context, *ent.PasskeyCredentialMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PasskeyCredentialFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PasskeyCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PasskeyCredentialMutation", m)
}

// The PasskeySessionFunc type is an adapter to allow the use of ordinary
// function as PasskeySession mutator.
type PasskeySessionFunc func(context.Context, *ent.PasskeySessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PasskeySessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PasskeySessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PasskeySessionMutation", m)
}

// The PasskeyTransportFunc type is an adapter to allow the use of ordinary
// function as PasskeyTransport mutator.
type PasskeyTransportFunc func(context.Context, *ent.PasskeyTransportMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PasskeyTransportFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PasskeyTransportMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PasskeyTransportMutation", m)
}

// The QuickUnlockDeviceFunc type is an adapter to allow the use of ordinary
// function as QuickUnlockDevice mutator.
type QuickUnlockDeviceFunc func(context.Context, *ent.QuickUnlockDeviceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f QuickUnlockDeviceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.QuickUnlockDeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.QuickUnlockDeviceMutation", m)
}

// The WebPushSubscriptionFunc type is an adapter to allow the use of ordinary
// function as WebPushSubscription mutator.
type WebPushSubscriptionFunc func(context.Context, *ent.WebPushSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WebPushSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WebPushSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WebPushSubscriptionMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
