// Code generated by ent, DO NOT EDIT.

package passkeytransport

import (
	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldContainsFold(FieldID, id))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldCredentialID, v))
}

// Transport applies equality check predicate on the "transport" field. It's identical to TransportEQ.
func Transport(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldTransport, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLTE(FieldCredentialID, v))
}

// CredentialIDContains applies the Contains predicate on the "credential_id" field.
func CredentialIDContains(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldContains(FieldCredentialID, v))
}

// CredentialIDHasPrefix applies the HasPrefix predicate on the "credential_id" field.
func CredentialIDHasPrefix(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldHasPrefix(FieldCredentialID, v))
}

// CredentialIDHasSuffix applies the HasSuffix predicate on the "credential_id" field.
func CredentialIDHasSuffix(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldHasSuffix(FieldCredentialID, v))
}

// CredentialIDEqualFold applies the EqualFold predicate on the "credential_id" field.
func CredentialIDEqualFold(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEqualFold(FieldCredentialID, v))
}

// CredentialIDContainsFold applies the ContainsFold predicate on the "credential_id" field.
func CredentialIDContainsFold(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldContainsFold(FieldCredentialID, v))
}

// TransportEQ applies the EQ predicate on the "transport" field.
func TransportEQ(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEQ(FieldTransport, v))
}

// TransportNEQ applies the NEQ predicate on the "transport" field.
func TransportNEQ(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNEQ(FieldTransport, v))
}

// TransportIn applies the In predicate on the "transport" field.
func TransportIn(vs ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldIn(FieldTransport, vs...))
}

// TransportNotIn applies the NotIn predicate on the "transport" field.
func TransportNotIn(vs ...string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldNotIn(FieldTransport, vs...))
}

// TransportGT applies the GT predicate on the "transport" field.
func TransportGT(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGT(FieldTransport, v))
}

// TransportGTE applies the GTE predicate on the "transport" field.
func TransportGTE(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldGTE(FieldTransport, v))
}

// TransportLT applies the LT predicate on the "transport" field.
func TransportLT(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLT(FieldTransport, v))
}

// TransportLTE applies the LTE predicate on the "transport" field.
func TransportLTE(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldLTE(FieldTransport, v))
}

// TransportContains applies the Contains predicate on the "transport" field.
func TransportContains(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldContains(FieldTransport, v))
}

// TransportHasPrefix applies the HasPrefix predicate on the "transport" field.
func TransportHasPrefix(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldHasPrefix(FieldTransport, v))
}

// TransportHasSuffix applies the HasSuffix predicate on the "transport" field.
func TransportHasSuffix(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldHasSuffix(FieldTransport, v))
}

// TransportEqualFold applies the EqualFold predicate on the "transport" field.
func TransportEqualFold(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldEqualFold(FieldTransport, v))
}

// TransportContainsFold applies the ContainsFold predicate on the "transport" field.
func TransportContainsFold(v string) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.FieldContainsFold(FieldTransport, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PasskeyTransport) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PasskeyTransport) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PasskeyTransport) predicate.PasskeyTransport {
	return predicate.PasskeyTransport(sql.NotPredicates(p))
}
