// Code generated by ent, DO NOT EDIT.

package gmailsynclease

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the gmailsynclease type in the database.
	Label = "gmail_sync_lease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "name"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// Table holds the table name of the gmailsynclease in the database.
	Table = "gmail_sync_leases"
)

// Columns holds all SQL columns for gmailsynclease fields.
var Columns = []string{
	FieldID,
	FieldOwner,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the GmailSyncLease queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}
