// Code generated by ent, DO NOT EDIT.

package gmailsynclease

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/borui/beancount-ledger-web/server/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldContainsFold(FieldID, id))
}

// Owner applies equality check predicate on the "owner" field. It's identical to OwnerEQ.
func Owner(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldOwner, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldExpiresAt, v))
}

// OwnerEQ applies the EQ predicate on the "owner" field.
func OwnerEQ(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldOwner, v))
}

// OwnerNEQ applies the NEQ predicate on the "owner" field.
func OwnerNEQ(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNEQ(FieldOwner, v))
}

// OwnerIn applies the In predicate on the "owner" field.
func OwnerIn(vs ...string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldIn(FieldOwner, vs...))
}

// OwnerNotIn applies the NotIn predicate on the "owner" field.
func OwnerNotIn(vs ...string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNotIn(FieldOwner, vs...))
}

// OwnerGT applies the GT predicate on the "owner" field.
func OwnerGT(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGT(FieldOwner, v))
}

// OwnerGTE applies the GTE predicate on the "owner" field.
func OwnerGTE(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGTE(FieldOwner, v))
}

// OwnerLT applies the LT predicate on the "owner" field.
func OwnerLT(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLT(FieldOwner, v))
}

// OwnerLTE applies the LTE predicate on the "owner" field.
func OwnerLTE(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLTE(FieldOwner, v))
}

// OwnerContains applies the Contains predicate on the "owner" field.
func OwnerContains(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldContains(FieldOwner, v))
}

// OwnerHasPrefix applies the HasPrefix predicate on the "owner" field.
func OwnerHasPrefix(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldHasPrefix(FieldOwner, v))
}

// OwnerHasSuffix applies the HasSuffix predicate on the "owner" field.
func OwnerHasSuffix(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldHasSuffix(FieldOwner, v))
}

// OwnerEqualFold applies the EqualFold predicate on the "owner" field.
func OwnerEqualFold(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEqualFold(FieldOwner, v))
}

// OwnerContainsFold applies the ContainsFold predicate on the "owner" field.
func OwnerContainsFold(v string) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldContainsFold(FieldOwner, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GmailSyncLease) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GmailSyncLease) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GmailSyncLease) predicate.GmailSyncLease {
	return predicate.GmailSyncLease(sql.NotPredicates(p))
}
