// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentApproval is the predicate function for agentapproval builders.
type AgentApproval func(*sql.Selector)

// AgentMemory is the predicate function for agentmemory builders.
type AgentMemory func(*sql.Selector)

// AgentSession is the predicate function for agentsession builders.
type AgentSession func(*sql.Selector)

// AgentSessionMessage is the predicate function for agentsessionmessage builders.
type AgentSessionMessage func(*sql.Selector)

// BQLHistoryRecord is the predicate function for bqlhistoryrecord builders.
type BQLHistoryRecord func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// PasskeyCredential is the predicate function for passkeycredential builders.
type PasskeyCredential func(*sql.Selector)

// PasskeySession is the predicate function for passkeysession builders.
type PasskeySession func(*sql.Selector)

// PasskeyTransport is the predicate function for passkeytransport builders.
type PasskeyTransport func(*sql.Selector)

// WebPushSubscription is the predicate function for webpushsubscription builders.
type WebPushSubscription func(*sql.Selector)
