// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BqlHistoryRecordsColumns holds the columns for the "bql_history_records" table.
	BqlHistoryRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "cluster_id", Type: field.TypeString},
		{Name: "query", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "title_source", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_run_at", Type: field.TypeTime},
		{Name: "run_count", Type: field.TypeInt},
	}
	// BqlHistoryRecordsTable holds the schema information for the "bql_history_records" table.
	BqlHistoryRecordsTable = &schema.Table{
		Name:       "bql_history_records",
		Columns:    BqlHistoryRecordsColumns,
		PrimaryKey: []*schema.Column{BqlHistoryRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bqlhistoryrecord_cluster_id_query",
				Unique:  true,
				Columns: []*schema.Column{BqlHistoryRecordsColumns[1], BqlHistoryRecordsColumns[2]},
			},
			{
				Name:    "bqlhistoryrecord_cluster_id_last_run_at",
				Unique:  false,
				Columns: []*schema.Column{BqlHistoryRecordsColumns[1], BqlHistoryRecordsColumns[6]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "insight_id", Type: field.TypeString},
		{Name: "month", Type: field.TypeString},
		{Name: "severity", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "detail", Type: field.TypeString},
		{Name: "detail_hash", Type: field.TypeString},
		{Name: "amount", Type: field.TypeInt, Nullable: true},
		{Name: "account", Type: field.TypeString, Nullable: true},
		{Name: "occurred_on", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "dismissed_at", Type: field.TypeTime, Nullable: true},
		{Name: "resolved_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "notification_month_insight_id",
				Unique:  true,
				Columns: []*schema.Column{NotificationsColumns[2], NotificationsColumns[1]},
			},
			{
				Name:    "notification_month_status_severity_updated_at",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[2], NotificationsColumns[10], NotificationsColumns[3], NotificationsColumns[15]},
			},
		},
	}
	// PasskeyCredentialsColumns holds the columns for the "passkey_credentials" table.
	PasskeyCredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeBytes},
		{Name: "sign_count", Type: field.TypeUint64},
		{Name: "backup_eligible", Type: field.TypeBool, Nullable: true},
		{Name: "backup_state", Type: field.TypeBool, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PasskeyCredentialsTable holds the schema information for the "passkey_credentials" table.
	PasskeyCredentialsTable = &schema.Table{
		Name:       "passkey_credentials",
		Columns:    PasskeyCredentialsColumns,
		PrimaryKey: []*schema.Column{PasskeyCredentialsColumns[0]},
	}
	// PasskeySessionsColumns holds the columns for the "passkey_sessions" table.
	PasskeySessionsColumns = []*schema.Column{
		{Name: "challenge", Type: field.TypeString},
		{Name: "data", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// PasskeySessionsTable holds the schema information for the "passkey_sessions" table.
	PasskeySessionsTable = &schema.Table{
		Name:       "passkey_sessions",
		Columns:    PasskeySessionsColumns,
		PrimaryKey: []*schema.Column{PasskeySessionsColumns[0]},
	}
	// PasskeyTransportsColumns holds the columns for the "passkey_transports" table.
	PasskeyTransportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "credential_id", Type: field.TypeString},
		{Name: "transport", Type: field.TypeString},
	}
	// PasskeyTransportsTable holds the schema information for the "passkey_transports" table.
	PasskeyTransportsTable = &schema.Table{
		Name:       "passkey_transports",
		Columns:    PasskeyTransportsColumns,
		PrimaryKey: []*schema.Column{PasskeyTransportsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "passkeytransport_credential_id_transport",
				Unique:  true,
				Columns: []*schema.Column{PasskeyTransportsColumns[1], PasskeyTransportsColumns[2]},
			},
		},
	}
	// WebPushSubscriptionsColumns holds the columns for the "web_push_subscriptions" table.
	WebPushSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "endpoint", Type: field.TypeString, Unique: true},
		{Name: "expiration_time", Type: field.TypeFloat64, Nullable: true},
		{Name: "auth_secret", Type: field.TypeString},
		{Name: "p256dh", Type: field.TypeString},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WebPushSubscriptionsTable holds the schema information for the "web_push_subscriptions" table.
	WebPushSubscriptionsTable = &schema.Table{
		Name:       "web_push_subscriptions",
		Columns:    WebPushSubscriptionsColumns,
		PrimaryKey: []*schema.Column{WebPushSubscriptionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BqlHistoryRecordsTable,
		NotificationsTable,
		PasskeyCredentialsTable,
		PasskeySessionsTable,
		PasskeyTransportsTable,
		WebPushSubscriptionsTable,
	}
)

func init() {
	BqlHistoryRecordsTable.Annotation = &entsql.Annotation{
		Table: "bql_history_records",
	}
	NotificationsTable.Annotation = &entsql.Annotation{
		Table: "notifications",
	}
	PasskeyCredentialsTable.Annotation = &entsql.Annotation{
		Table: "passkey_credentials",
	}
	PasskeySessionsTable.Annotation = &entsql.Annotation{
		Table: "passkey_sessions",
	}
	PasskeyTransportsTable.Annotation = &entsql.Annotation{
		Table: "passkey_transports",
	}
	WebPushSubscriptionsTable.Annotation = &entsql.Annotation{
		Table: "web_push_subscriptions",
	}
}
